// Code generated by go-swagger; DO NOT EDIT.

package networks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "git.f-i-ts.de/cloud-native/metal/metal-api/netbox-api/models"
)

// NetboxAPIProxyAPICreateNetworkReader is a Reader for the NetboxAPIProxyAPICreateNetwork structure.
type NetboxAPIProxyAPICreateNetworkReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *NetboxAPIProxyAPICreateNetworkReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewNetboxAPIProxyAPICreateNetworkOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewNetboxAPIProxyAPICreateNetworkDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewNetboxAPIProxyAPICreateNetworkOK creates a NetboxAPIProxyAPICreateNetworkOK with default headers values
func NewNetboxAPIProxyAPICreateNetworkOK() *NetboxAPIProxyAPICreateNetworkOK {
	return &NetboxAPIProxyAPICreateNetworkOK{}
}

/*NetboxAPIProxyAPICreateNetworkOK handles this case with default header values.

OK
*/
type NetboxAPIProxyAPICreateNetworkOK struct {
}

func (o *NetboxAPIProxyAPICreateNetworkOK) Error() string {
	return fmt.Sprintf("[POST /networks][%d] netboxApiProxyApiCreateNetworkOK ", 200)
}

func (o *NetboxAPIProxyAPICreateNetworkOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNetboxAPIProxyAPICreateNetworkDefault creates a NetboxAPIProxyAPICreateNetworkDefault with default headers values
func NewNetboxAPIProxyAPICreateNetworkDefault(code int) *NetboxAPIProxyAPICreateNetworkDefault {
	return &NetboxAPIProxyAPICreateNetworkDefault{
		_statusCode: code,
	}
}

/*NetboxAPIProxyAPICreateNetworkDefault handles this case with default header values.

Problem
*/
type NetboxAPIProxyAPICreateNetworkDefault struct {
	_statusCode int

	Payload *models.Problem
}

// Code gets the status code for the netbox api proxy api create network default response
func (o *NetboxAPIProxyAPICreateNetworkDefault) Code() int {
	return o._statusCode
}

func (o *NetboxAPIProxyAPICreateNetworkDefault) Error() string {
	return fmt.Sprintf("[POST /networks][%d] netbox_api_proxy.api.create_network default  %+v", o._statusCode, o.Payload)
}

func (o *NetboxAPIProxyAPICreateNetworkDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Problem)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
