// Code generated by go-swagger; DO NOT EDIT.

package networks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "git.f-i-ts.de/cloud-native/metal/metal-api/netbox-api/models"
)

// NetboxAPIProxyAPIDeleteNetworkReader is a Reader for the NetboxAPIProxyAPIDeleteNetwork structure.
type NetboxAPIProxyAPIDeleteNetworkReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *NetboxAPIProxyAPIDeleteNetworkReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewNetboxAPIProxyAPIDeleteNetworkOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewNetboxAPIProxyAPIDeleteNetworkDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewNetboxAPIProxyAPIDeleteNetworkOK creates a NetboxAPIProxyAPIDeleteNetworkOK with default headers values
func NewNetboxAPIProxyAPIDeleteNetworkOK() *NetboxAPIProxyAPIDeleteNetworkOK {
	return &NetboxAPIProxyAPIDeleteNetworkOK{}
}

/*NetboxAPIProxyAPIDeleteNetworkOK handles this case with default header values.

OK
*/
type NetboxAPIProxyAPIDeleteNetworkOK struct {
}

func (o *NetboxAPIProxyAPIDeleteNetworkOK) Error() string {
	return fmt.Sprintf("[DELETE /networks][%d] netboxApiProxyApiDeleteNetworkOK ", 200)
}

func (o *NetboxAPIProxyAPIDeleteNetworkOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNetboxAPIProxyAPIDeleteNetworkDefault creates a NetboxAPIProxyAPIDeleteNetworkDefault with default headers values
func NewNetboxAPIProxyAPIDeleteNetworkDefault(code int) *NetboxAPIProxyAPIDeleteNetworkDefault {
	return &NetboxAPIProxyAPIDeleteNetworkDefault{
		_statusCode: code,
	}
}

/*NetboxAPIProxyAPIDeleteNetworkDefault handles this case with default header values.

Problem
*/
type NetboxAPIProxyAPIDeleteNetworkDefault struct {
	_statusCode int

	Payload *models.Problem
}

// Code gets the status code for the netbox api proxy api delete network default response
func (o *NetboxAPIProxyAPIDeleteNetworkDefault) Code() int {
	return o._statusCode
}

func (o *NetboxAPIProxyAPIDeleteNetworkDefault) Error() string {
	return fmt.Sprintf("[DELETE /networks][%d] netbox_api_proxy.api.delete_network default  %+v", o._statusCode, o.Payload)
}

func (o *NetboxAPIProxyAPIDeleteNetworkDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Problem)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
