// Code generated by go-swagger; DO NOT EDIT.

package networks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "git.f-i-ts.de/cloud-native/metal/metal-api/netbox-api/models"
)

// NewNetboxAPIProxyAPICreateNetworkParams creates a new NetboxAPIProxyAPICreateNetworkParams object
// with the default values initialized.
func NewNetboxAPIProxyAPICreateNetworkParams() *NetboxAPIProxyAPICreateNetworkParams {
	var ()
	return &NetboxAPIProxyAPICreateNetworkParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewNetboxAPIProxyAPICreateNetworkParamsWithTimeout creates a new NetboxAPIProxyAPICreateNetworkParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewNetboxAPIProxyAPICreateNetworkParamsWithTimeout(timeout time.Duration) *NetboxAPIProxyAPICreateNetworkParams {
	var ()
	return &NetboxAPIProxyAPICreateNetworkParams{

		timeout: timeout,
	}
}

// NewNetboxAPIProxyAPICreateNetworkParamsWithContext creates a new NetboxAPIProxyAPICreateNetworkParams object
// with the default values initialized, and the ability to set a context for a request
func NewNetboxAPIProxyAPICreateNetworkParamsWithContext(ctx context.Context) *NetboxAPIProxyAPICreateNetworkParams {
	var ()
	return &NetboxAPIProxyAPICreateNetworkParams{

		Context: ctx,
	}
}

// NewNetboxAPIProxyAPICreateNetworkParamsWithHTTPClient creates a new NetboxAPIProxyAPICreateNetworkParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewNetboxAPIProxyAPICreateNetworkParamsWithHTTPClient(client *http.Client) *NetboxAPIProxyAPICreateNetworkParams {
	var ()
	return &NetboxAPIProxyAPICreateNetworkParams{
		HTTPClient: client,
	}
}

/*NetboxAPIProxyAPICreateNetworkParams contains all the parameters to send to the API endpoint
for the netbox api proxy api create network operation typically these are written to a http.Request
*/
type NetboxAPIProxyAPICreateNetworkParams struct {

	/*Request
	  The network creation body

	*/
	Request *models.NetworkCreateRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the netbox api proxy api create network params
func (o *NetboxAPIProxyAPICreateNetworkParams) WithTimeout(timeout time.Duration) *NetboxAPIProxyAPICreateNetworkParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the netbox api proxy api create network params
func (o *NetboxAPIProxyAPICreateNetworkParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the netbox api proxy api create network params
func (o *NetboxAPIProxyAPICreateNetworkParams) WithContext(ctx context.Context) *NetboxAPIProxyAPICreateNetworkParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the netbox api proxy api create network params
func (o *NetboxAPIProxyAPICreateNetworkParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the netbox api proxy api create network params
func (o *NetboxAPIProxyAPICreateNetworkParams) WithHTTPClient(client *http.Client) *NetboxAPIProxyAPICreateNetworkParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the netbox api proxy api create network params
func (o *NetboxAPIProxyAPICreateNetworkParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the netbox api proxy api create network params
func (o *NetboxAPIProxyAPICreateNetworkParams) WithRequest(request *models.NetworkCreateRequest) *NetboxAPIProxyAPICreateNetworkParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the netbox api proxy api create network params
func (o *NetboxAPIProxyAPICreateNetworkParams) SetRequest(request *models.NetworkCreateRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *NetboxAPIProxyAPICreateNetworkParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
