// Code generated by go-swagger; DO NOT EDIT.

package networks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "git.f-i-ts.de/cloud-native/metal/metal-api/netbox-api/models"
)

// NewNetboxAPIProxyAPIDeleteNetworkParams creates a new NetboxAPIProxyAPIDeleteNetworkParams object
// with the default values initialized.
func NewNetboxAPIProxyAPIDeleteNetworkParams() *NetboxAPIProxyAPIDeleteNetworkParams {
	var ()
	return &NetboxAPIProxyAPIDeleteNetworkParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewNetboxAPIProxyAPIDeleteNetworkParamsWithTimeout creates a new NetboxAPIProxyAPIDeleteNetworkParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewNetboxAPIProxyAPIDeleteNetworkParamsWithTimeout(timeout time.Duration) *NetboxAPIProxyAPIDeleteNetworkParams {
	var ()
	return &NetboxAPIProxyAPIDeleteNetworkParams{

		timeout: timeout,
	}
}

// NewNetboxAPIProxyAPIDeleteNetworkParamsWithContext creates a new NetboxAPIProxyAPIDeleteNetworkParams object
// with the default values initialized, and the ability to set a context for a request
func NewNetboxAPIProxyAPIDeleteNetworkParamsWithContext(ctx context.Context) *NetboxAPIProxyAPIDeleteNetworkParams {
	var ()
	return &NetboxAPIProxyAPIDeleteNetworkParams{

		Context: ctx,
	}
}

// NewNetboxAPIProxyAPIDeleteNetworkParamsWithHTTPClient creates a new NetboxAPIProxyAPIDeleteNetworkParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewNetboxAPIProxyAPIDeleteNetworkParamsWithHTTPClient(client *http.Client) *NetboxAPIProxyAPIDeleteNetworkParams {
	var ()
	return &NetboxAPIProxyAPIDeleteNetworkParams{
		HTTPClient: client,
	}
}

/*NetboxAPIProxyAPIDeleteNetworkParams contains all the parameters to send to the API endpoint
for the netbox api proxy api delete network operation typically these are written to a http.Request
*/
type NetboxAPIProxyAPIDeleteNetworkParams struct {

	/*Request
	  The ip deletion body

	*/
	Request *models.CIDR

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the netbox api proxy api delete network params
func (o *NetboxAPIProxyAPIDeleteNetworkParams) WithTimeout(timeout time.Duration) *NetboxAPIProxyAPIDeleteNetworkParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the netbox api proxy api delete network params
func (o *NetboxAPIProxyAPIDeleteNetworkParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the netbox api proxy api delete network params
func (o *NetboxAPIProxyAPIDeleteNetworkParams) WithContext(ctx context.Context) *NetboxAPIProxyAPIDeleteNetworkParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the netbox api proxy api delete network params
func (o *NetboxAPIProxyAPIDeleteNetworkParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the netbox api proxy api delete network params
func (o *NetboxAPIProxyAPIDeleteNetworkParams) WithHTTPClient(client *http.Client) *NetboxAPIProxyAPIDeleteNetworkParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the netbox api proxy api delete network params
func (o *NetboxAPIProxyAPIDeleteNetworkParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the netbox api proxy api delete network params
func (o *NetboxAPIProxyAPIDeleteNetworkParams) WithRequest(request *models.CIDR) *NetboxAPIProxyAPIDeleteNetworkParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the netbox api proxy api delete network params
func (o *NetboxAPIProxyAPIDeleteNetworkParams) SetRequest(request *models.CIDR) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *NetboxAPIProxyAPIDeleteNetworkParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
