// Code generated by go-swagger; DO NOT EDIT.

package devices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "git.f-i-ts.de/cloud-native/metal/metal-api/netbox-api/models"
)

// NewNetboxAPIProxyAPIDeviceAllocateParams creates a new NetboxAPIProxyAPIDeviceAllocateParams object
// with the default values initialized.
func NewNetboxAPIProxyAPIDeviceAllocateParams() *NetboxAPIProxyAPIDeviceAllocateParams {
	var ()
	return &NetboxAPIProxyAPIDeviceAllocateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewNetboxAPIProxyAPIDeviceAllocateParamsWithTimeout creates a new NetboxAPIProxyAPIDeviceAllocateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewNetboxAPIProxyAPIDeviceAllocateParamsWithTimeout(timeout time.Duration) *NetboxAPIProxyAPIDeviceAllocateParams {
	var ()
	return &NetboxAPIProxyAPIDeviceAllocateParams{

		timeout: timeout,
	}
}

// NewNetboxAPIProxyAPIDeviceAllocateParamsWithContext creates a new NetboxAPIProxyAPIDeviceAllocateParams object
// with the default values initialized, and the ability to set a context for a request
func NewNetboxAPIProxyAPIDeviceAllocateParamsWithContext(ctx context.Context) *NetboxAPIProxyAPIDeviceAllocateParams {
	var ()
	return &NetboxAPIProxyAPIDeviceAllocateParams{

		Context: ctx,
	}
}

// NewNetboxAPIProxyAPIDeviceAllocateParamsWithHTTPClient creates a new NetboxAPIProxyAPIDeviceAllocateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewNetboxAPIProxyAPIDeviceAllocateParamsWithHTTPClient(client *http.Client) *NetboxAPIProxyAPIDeviceAllocateParams {
	var ()
	return &NetboxAPIProxyAPIDeviceAllocateParams{
		HTTPClient: client,
	}
}

/*NetboxAPIProxyAPIDeviceAllocateParams contains all the parameters to send to the API endpoint
for the netbox api proxy api device allocate operation typically these are written to a http.Request
*/
type NetboxAPIProxyAPIDeviceAllocateParams struct {

	/*Request
	  The device allocation body

	*/
	Request *models.DeviceAllocationRequest
	/*UUID
	  The product serial of the device (unique identifier of this device)

	*/
	UUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the netbox api proxy api device allocate params
func (o *NetboxAPIProxyAPIDeviceAllocateParams) WithTimeout(timeout time.Duration) *NetboxAPIProxyAPIDeviceAllocateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the netbox api proxy api device allocate params
func (o *NetboxAPIProxyAPIDeviceAllocateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the netbox api proxy api device allocate params
func (o *NetboxAPIProxyAPIDeviceAllocateParams) WithContext(ctx context.Context) *NetboxAPIProxyAPIDeviceAllocateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the netbox api proxy api device allocate params
func (o *NetboxAPIProxyAPIDeviceAllocateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the netbox api proxy api device allocate params
func (o *NetboxAPIProxyAPIDeviceAllocateParams) WithHTTPClient(client *http.Client) *NetboxAPIProxyAPIDeviceAllocateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the netbox api proxy api device allocate params
func (o *NetboxAPIProxyAPIDeviceAllocateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the netbox api proxy api device allocate params
func (o *NetboxAPIProxyAPIDeviceAllocateParams) WithRequest(request *models.DeviceAllocationRequest) *NetboxAPIProxyAPIDeviceAllocateParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the netbox api proxy api device allocate params
func (o *NetboxAPIProxyAPIDeviceAllocateParams) SetRequest(request *models.DeviceAllocationRequest) {
	o.Request = request
}

// WithUUID adds the uuid to the netbox api proxy api device allocate params
func (o *NetboxAPIProxyAPIDeviceAllocateParams) WithUUID(uuid string) *NetboxAPIProxyAPIDeviceAllocateParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the netbox api proxy api device allocate params
func (o *NetboxAPIProxyAPIDeviceAllocateParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *NetboxAPIProxyAPIDeviceAllocateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
