// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DeviceRegistrationRequest device registration request
// swagger:model DeviceRegistrationRequest
type DeviceRegistrationRequest struct {

	// The network interfaces of this device
	// Required: true
	Nics []*Nic `json:"nics"`

	// The name of the rack
	// Required: true
	Rack *string `json:"rack"`

	// The id of the site
	// Required: true
	Site *string `json:"site"`

	// The size of the device
	// Required: true
	// Enum: [t1.small.x86]
	Size *string `json:"size"`
}

// Validate validates this device registration request
func (m *DeviceRegistrationRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateNics(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRack(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSite(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSize(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DeviceRegistrationRequest) validateNics(formats strfmt.Registry) error {

	if err := validate.Required("nics", "body", m.Nics); err != nil {
		return err
	}

	for i := 0; i < len(m.Nics); i++ {
		if swag.IsZero(m.Nics[i]) { // not required
			continue
		}

		if m.Nics[i] != nil {
			if err := m.Nics[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("nics" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *DeviceRegistrationRequest) validateRack(formats strfmt.Registry) error {

	if err := validate.Required("rack", "body", m.Rack); err != nil {
		return err
	}

	return nil
}

func (m *DeviceRegistrationRequest) validateSite(formats strfmt.Registry) error {

	if err := validate.Required("site", "body", m.Site); err != nil {
		return err
	}

	return nil
}

var deviceRegistrationRequestTypeSizePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["t1.small.x86"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		deviceRegistrationRequestTypeSizePropEnum = append(deviceRegistrationRequestTypeSizePropEnum, v)
	}
}

const (

	// DeviceRegistrationRequestSizeT1SmallX86 captures enum value "t1.small.x86"
	DeviceRegistrationRequestSizeT1SmallX86 string = "t1.small.x86"
)

// prop value enum
func (m *DeviceRegistrationRequest) validateSizeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, deviceRegistrationRequestTypeSizePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *DeviceRegistrationRequest) validateSize(formats strfmt.Registry) error {

	if err := validate.Required("size", "body", m.Size); err != nil {
		return err
	}

	// value enum
	if err := m.validateSizeEnum("size", "body", *m.Size); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DeviceRegistrationRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeviceRegistrationRequest) UnmarshalBinary(b []byte) error {
	var res DeviceRegistrationRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
