// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SwitchRegistrationRequest switch registration request
// swagger:model SwitchRegistrationRequest
type SwitchRegistrationRequest struct {

	// The desired name for this device in the netbox
	// Required: true
	// Min Length: 1
	Name *string `json:"name"`

	// The network interfaces of this device
	// Required: true
	Nics []*Nic `json:"nics"`

	// The name of the rack
	// Required: true
	// Min Length: 1
	Rack *string `json:"rack"`

	// The id of the site
	// Required: true
	// Min Length: 1
	Site *string `json:"site"`
}

// Validate validates this switch registration request
func (m *SwitchRegistrationRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNics(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRack(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSite(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SwitchRegistrationRequest) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	if err := validate.MinLength("name", "body", string(*m.Name), 1); err != nil {
		return err
	}

	return nil
}

func (m *SwitchRegistrationRequest) validateNics(formats strfmt.Registry) error {

	if err := validate.Required("nics", "body", m.Nics); err != nil {
		return err
	}

	for i := 0; i < len(m.Nics); i++ {
		if swag.IsZero(m.Nics[i]) { // not required
			continue
		}

		if m.Nics[i] != nil {
			if err := m.Nics[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("nics" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *SwitchRegistrationRequest) validateRack(formats strfmt.Registry) error {

	if err := validate.Required("rack", "body", m.Rack); err != nil {
		return err
	}

	if err := validate.MinLength("rack", "body", string(*m.Rack), 1); err != nil {
		return err
	}

	return nil
}

func (m *SwitchRegistrationRequest) validateSite(formats strfmt.Registry) error {

	if err := validate.Required("site", "body", m.Site); err != nil {
		return err
	}

	if err := validate.MinLength("site", "body", string(*m.Site), 1); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SwitchRegistrationRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SwitchRegistrationRequest) UnmarshalBinary(b []byte) error {
	var res SwitchRegistrationRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
