// Code generated by go-swagger; DO NOT EDIT.

package switches

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "git.f-i-ts.de/cloud-native/metal/metal-api/netbox-api/models"
)

// NetboxAPIProxyAPISwitchRegisterReader is a Reader for the NetboxAPIProxyAPISwitchRegister structure.
type NetboxAPIProxyAPISwitchRegisterReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *NetboxAPIProxyAPISwitchRegisterReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewNetboxAPIProxyAPISwitchRegisterOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewNetboxAPIProxyAPISwitchRegisterDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewNetboxAPIProxyAPISwitchRegisterOK creates a NetboxAPIProxyAPISwitchRegisterOK with default headers values
func NewNetboxAPIProxyAPISwitchRegisterOK() *NetboxAPIProxyAPISwitchRegisterOK {
	return &NetboxAPIProxyAPISwitchRegisterOK{}
}

/*NetboxAPIProxyAPISwitchRegisterOK handles this case with default header values.

OK
*/
type NetboxAPIProxyAPISwitchRegisterOK struct {
}

func (o *NetboxAPIProxyAPISwitchRegisterOK) Error() string {
	return fmt.Sprintf("[POST /switches/{uuid}/register][%d] netboxApiProxyApiSwitchRegisterOK ", 200)
}

func (o *NetboxAPIProxyAPISwitchRegisterOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNetboxAPIProxyAPISwitchRegisterDefault creates a NetboxAPIProxyAPISwitchRegisterDefault with default headers values
func NewNetboxAPIProxyAPISwitchRegisterDefault(code int) *NetboxAPIProxyAPISwitchRegisterDefault {
	return &NetboxAPIProxyAPISwitchRegisterDefault{
		_statusCode: code,
	}
}

/*NetboxAPIProxyAPISwitchRegisterDefault handles this case with default header values.

Problem
*/
type NetboxAPIProxyAPISwitchRegisterDefault struct {
	_statusCode int

	Payload *models.Problem
}

// Code gets the status code for the netbox api proxy api switch register default response
func (o *NetboxAPIProxyAPISwitchRegisterDefault) Code() int {
	return o._statusCode
}

func (o *NetboxAPIProxyAPISwitchRegisterDefault) Error() string {
	return fmt.Sprintf("[POST /switches/{uuid}/register][%d] netbox_api_proxy.api.switch_register default  %+v", o._statusCode, o.Payload)
}

func (o *NetboxAPIProxyAPISwitchRegisterDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Problem)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
