// Code generated by go-swagger; DO NOT EDIT.

package switches

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new switches API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for switches API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
NetboxAPIProxyAPISwitchRegister registers a new switch

Register a new switch to the netbox
*/
func (a *Client) NetboxAPIProxyAPISwitchRegister(params *NetboxAPIProxyAPISwitchRegisterParams, authInfo runtime.ClientAuthInfoWriter) (*NetboxAPIProxyAPISwitchRegisterOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewNetboxAPIProxyAPISwitchRegisterParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "netbox_api_proxy.api.switch_register",
		Method:             "POST",
		PathPattern:        "/switches/{uuid}/register",
		ProducesMediaTypes: []string{"application/json", "application/problem+json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &NetboxAPIProxyAPISwitchRegisterReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*NetboxAPIProxyAPISwitchRegisterOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
