// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/v1/boot.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BootServiceDhcpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootServiceDhcpRequest) Reset() {
	*x = BootServiceDhcpRequest{}
	mi := &file_api_v1_boot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootServiceDhcpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootServiceDhcpRequest) ProtoMessage() {}

func (x *BootServiceDhcpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_boot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootServiceDhcpRequest.ProtoReflect.Descriptor instead.
func (*BootServiceDhcpRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_boot_proto_rawDescGZIP(), []int{0}
}

func (x *BootServiceDhcpRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type BootServiceDhcpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootServiceDhcpResponse) Reset() {
	*x = BootServiceDhcpResponse{}
	mi := &file_api_v1_boot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootServiceDhcpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootServiceDhcpResponse) ProtoMessage() {}

func (x *BootServiceDhcpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_boot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootServiceDhcpResponse.ProtoReflect.Descriptor instead.
func (*BootServiceDhcpResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_boot_proto_rawDescGZIP(), []int{1}
}

type BootServiceBootRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mac           string                 `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"`
	PartitionId   string                 `protobuf:"bytes,2,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootServiceBootRequest) Reset() {
	*x = BootServiceBootRequest{}
	mi := &file_api_v1_boot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootServiceBootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootServiceBootRequest) ProtoMessage() {}

func (x *BootServiceBootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_boot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootServiceBootRequest.ProtoReflect.Descriptor instead.
func (*BootServiceBootRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_boot_proto_rawDescGZIP(), []int{2}
}

func (x *BootServiceBootRequest) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *BootServiceBootRequest) GetPartitionId() string {
	if x != nil {
		return x.PartitionId
	}
	return ""
}

type BootServiceBootResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kernel        string                 `protobuf:"bytes,1,opt,name=kernel,proto3" json:"kernel,omitempty"`
	InitRamDisks  []string               `protobuf:"bytes,2,rep,name=init_ram_disks,json=initRamDisks,proto3" json:"init_ram_disks,omitempty"`
	Cmdline       *string                `protobuf:"bytes,3,opt,name=cmdline,proto3,oneof" json:"cmdline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootServiceBootResponse) Reset() {
	*x = BootServiceBootResponse{}
	mi := &file_api_v1_boot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootServiceBootResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootServiceBootResponse) ProtoMessage() {}

func (x *BootServiceBootResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_boot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootServiceBootResponse.ProtoReflect.Descriptor instead.
func (*BootServiceBootResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_boot_proto_rawDescGZIP(), []int{3}
}

func (x *BootServiceBootResponse) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

func (x *BootServiceBootResponse) GetInitRamDisks() []string {
	if x != nil {
		return x.InitRamDisks
	}
	return nil
}

func (x *BootServiceBootResponse) GetCmdline() string {
	if x != nil && x.Cmdline != nil {
		return *x.Cmdline
	}
	return ""
}

type BootServiceRegisterRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Uuid               string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Hardware           *MachineHardware       `protobuf:"bytes,2,opt,name=hardware,proto3" json:"hardware,omitempty"`
	Bios               *MachineBIOS           `protobuf:"bytes,3,opt,name=bios,proto3" json:"bios,omitempty"`
	Ipmi               *MachineIPMI           `protobuf:"bytes,4,opt,name=ipmi,proto3" json:"ipmi,omitempty"`
	Tags               []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	MetalHammerVersion string                 `protobuf:"bytes,6,opt,name=metal_hammer_version,json=metalHammerVersion,proto3" json:"metal_hammer_version,omitempty"`
	PartitionId        string                 `protobuf:"bytes,7,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BootServiceRegisterRequest) Reset() {
	*x = BootServiceRegisterRequest{}
	mi := &file_api_v1_boot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootServiceRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootServiceRegisterRequest) ProtoMessage() {}

func (x *BootServiceRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_boot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootServiceRegisterRequest.ProtoReflect.Descriptor instead.
func (*BootServiceRegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_boot_proto_rawDescGZIP(), []int{4}
}

func (x *BootServiceRegisterRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *BootServiceRegisterRequest) GetHardware() *MachineHardware {
	if x != nil {
		return x.Hardware
	}
	return nil
}

func (x *BootServiceRegisterRequest) GetBios() *MachineBIOS {
	if x != nil {
		return x.Bios
	}
	return nil
}

func (x *BootServiceRegisterRequest) GetIpmi() *MachineIPMI {
	if x != nil {
		return x.Ipmi
	}
	return nil
}

func (x *BootServiceRegisterRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *BootServiceRegisterRequest) GetMetalHammerVersion() string {
	if x != nil {
		return x.MetalHammerVersion
	}
	return ""
}

func (x *BootServiceRegisterRequest) GetPartitionId() string {
	if x != nil {
		return x.PartitionId
	}
	return ""
}

type BootServiceRegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Size          string                 `protobuf:"bytes,2,opt,name=size,proto3" json:"size,omitempty"`
	PartitionId   string                 `protobuf:"bytes,3,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootServiceRegisterResponse) Reset() {
	*x = BootServiceRegisterResponse{}
	mi := &file_api_v1_boot_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootServiceRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootServiceRegisterResponse) ProtoMessage() {}

func (x *BootServiceRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_boot_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootServiceRegisterResponse.ProtoReflect.Descriptor instead.
func (*BootServiceRegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_boot_proto_rawDescGZIP(), []int{5}
}

func (x *BootServiceRegisterResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *BootServiceRegisterResponse) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *BootServiceRegisterResponse) GetPartitionId() string {
	if x != nil {
		return x.PartitionId
	}
	return ""
}

type BootServiceWaitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineId     string                 `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootServiceWaitRequest) Reset() {
	*x = BootServiceWaitRequest{}
	mi := &file_api_v1_boot_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootServiceWaitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootServiceWaitRequest) ProtoMessage() {}

func (x *BootServiceWaitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_boot_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootServiceWaitRequest.ProtoReflect.Descriptor instead.
func (*BootServiceWaitRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_boot_proto_rawDescGZIP(), []int{6}
}

func (x *BootServiceWaitRequest) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

type BootServiceWaitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootServiceWaitResponse) Reset() {
	*x = BootServiceWaitResponse{}
	mi := &file_api_v1_boot_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootServiceWaitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootServiceWaitResponse) ProtoMessage() {}

func (x *BootServiceWaitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_boot_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootServiceWaitResponse.ProtoReflect.Descriptor instead.
func (*BootServiceWaitResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_boot_proto_rawDescGZIP(), []int{7}
}

type MachineHardware struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memory        uint64                 `protobuf:"varint,1,opt,name=memory,proto3" json:"memory,omitempty"`
	Disks         []*MachineBlockDevice  `protobuf:"bytes,3,rep,name=disks,proto3" json:"disks,omitempty"`
	Nics          []*MachineNic          `protobuf:"bytes,4,rep,name=nics,proto3" json:"nics,omitempty"`
	Cpus          []*MachineCPU          `protobuf:"bytes,5,rep,name=cpus,proto3" json:"cpus,omitempty"`
	Gpus          []*MachineGPU          `protobuf:"bytes,6,rep,name=gpus,proto3" json:"gpus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineHardware) Reset() {
	*x = MachineHardware{}
	mi := &file_api_v1_boot_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineHardware) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineHardware) ProtoMessage() {}

func (x *MachineHardware) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_boot_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineHardware.ProtoReflect.Descriptor instead.
func (*MachineHardware) Descriptor() ([]byte, []int) {
	return file_api_v1_boot_proto_rawDescGZIP(), []int{8}
}

func (x *MachineHardware) GetMemory() uint64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *MachineHardware) GetDisks() []*MachineBlockDevice {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *MachineHardware) GetNics() []*MachineNic {
	if x != nil {
		return x.Nics
	}
	return nil
}

func (x *MachineHardware) GetCpus() []*MachineCPU {
	if x != nil {
		return x.Cpus
	}
	return nil
}

func (x *MachineHardware) GetGpus() []*MachineGPU {
	if x != nil {
		return x.Gpus
	}
	return nil
}

type MachineCPU struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vendor        string                 `protobuf:"bytes,1,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Cores         uint32                 `protobuf:"varint,3,opt,name=cores,proto3" json:"cores,omitempty"`
	Threads       uint32                 `protobuf:"varint,4,opt,name=threads,proto3" json:"threads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineCPU) Reset() {
	*x = MachineCPU{}
	mi := &file_api_v1_boot_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineCPU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineCPU) ProtoMessage() {}

func (x *MachineCPU) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_boot_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineCPU.ProtoReflect.Descriptor instead.
func (*MachineCPU) Descriptor() ([]byte, []int) {
	return file_api_v1_boot_proto_rawDescGZIP(), []int{9}
}

func (x *MachineCPU) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *MachineCPU) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *MachineCPU) GetCores() uint32 {
	if x != nil {
		return x.Cores
	}
	return 0
}

func (x *MachineCPU) GetThreads() uint32 {
	if x != nil {
		return x.Threads
	}
	return 0
}

type MachineGPU struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vendor        string                 `protobuf:"bytes,1,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineGPU) Reset() {
	*x = MachineGPU{}
	mi := &file_api_v1_boot_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineGPU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineGPU) ProtoMessage() {}

func (x *MachineGPU) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_boot_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineGPU.ProtoReflect.Descriptor instead.
func (*MachineGPU) Descriptor() ([]byte, []int) {
	return file_api_v1_boot_proto_rawDescGZIP(), []int{10}
}

func (x *MachineGPU) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *MachineGPU) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type MachineNic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mac           string                 `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Neighbors     []*MachineNic          `protobuf:"bytes,3,rep,name=neighbors,proto3" json:"neighbors,omitempty"`
	Hostname      string                 `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Identifier    string                 `protobuf:"bytes,5,opt,name=identifier,proto3" json:"identifier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineNic) Reset() {
	*x = MachineNic{}
	mi := &file_api_v1_boot_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineNic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineNic) ProtoMessage() {}

func (x *MachineNic) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_boot_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineNic.ProtoReflect.Descriptor instead.
func (*MachineNic) Descriptor() ([]byte, []int) {
	return file_api_v1_boot_proto_rawDescGZIP(), []int{11}
}

func (x *MachineNic) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *MachineNic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MachineNic) GetNeighbors() []*MachineNic {
	if x != nil {
		return x.Neighbors
	}
	return nil
}

func (x *MachineNic) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *MachineNic) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

type MachineBlockDevice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Size          uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineBlockDevice) Reset() {
	*x = MachineBlockDevice{}
	mi := &file_api_v1_boot_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineBlockDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineBlockDevice) ProtoMessage() {}

func (x *MachineBlockDevice) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_boot_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineBlockDevice.ProtoReflect.Descriptor instead.
func (*MachineBlockDevice) Descriptor() ([]byte, []int) {
	return file_api_v1_boot_proto_rawDescGZIP(), []int{12}
}

func (x *MachineBlockDevice) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MachineBlockDevice) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type MachineBIOS struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Vendor        string                 `protobuf:"bytes,2,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineBIOS) Reset() {
	*x = MachineBIOS{}
	mi := &file_api_v1_boot_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineBIOS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineBIOS) ProtoMessage() {}

func (x *MachineBIOS) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_boot_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineBIOS.ProtoReflect.Descriptor instead.
func (*MachineBIOS) Descriptor() ([]byte, []int) {
	return file_api_v1_boot_proto_rawDescGZIP(), []int{13}
}

func (x *MachineBIOS) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *MachineBIOS) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *MachineBIOS) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type MachineIPMI struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Mac           string                 `protobuf:"bytes,2,opt,name=mac,proto3" json:"mac,omitempty"`
	User          string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Interface     string                 `protobuf:"bytes,5,opt,name=interface,proto3" json:"interface,omitempty"`
	Fru           *MachineFRU            `protobuf:"bytes,6,opt,name=fru,proto3" json:"fru,omitempty"`
	BmcVersion    string                 `protobuf:"bytes,7,opt,name=bmc_version,json=bmcVersion,proto3" json:"bmc_version,omitempty"`
	PowerState    string                 `protobuf:"bytes,8,opt,name=power_state,json=powerState,proto3" json:"power_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineIPMI) Reset() {
	*x = MachineIPMI{}
	mi := &file_api_v1_boot_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineIPMI) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineIPMI) ProtoMessage() {}

func (x *MachineIPMI) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_boot_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineIPMI.ProtoReflect.Descriptor instead.
func (*MachineIPMI) Descriptor() ([]byte, []int) {
	return file_api_v1_boot_proto_rawDescGZIP(), []int{14}
}

func (x *MachineIPMI) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *MachineIPMI) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *MachineIPMI) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *MachineIPMI) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *MachineIPMI) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *MachineIPMI) GetFru() *MachineFRU {
	if x != nil {
		return x.Fru
	}
	return nil
}

func (x *MachineIPMI) GetBmcVersion() string {
	if x != nil {
		return x.BmcVersion
	}
	return ""
}

func (x *MachineIPMI) GetPowerState() string {
	if x != nil {
		return x.PowerState
	}
	return ""
}

type MachineFRU struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ChassisPartNumber   *string                `protobuf:"bytes,1,opt,name=chassis_part_number,json=chassisPartNumber,proto3,oneof" json:"chassis_part_number,omitempty"`
	ChassisPartSerial   *string                `protobuf:"bytes,2,opt,name=chassis_part_serial,json=chassisPartSerial,proto3,oneof" json:"chassis_part_serial,omitempty"`
	BoardMfg            *string                `protobuf:"bytes,3,opt,name=board_mfg,json=boardMfg,proto3,oneof" json:"board_mfg,omitempty"`
	BoardMfgSerial      *string                `protobuf:"bytes,4,opt,name=board_mfg_serial,json=boardMfgSerial,proto3,oneof" json:"board_mfg_serial,omitempty"`
	BoardPartNumber     *string                `protobuf:"bytes,5,opt,name=board_part_number,json=boardPartNumber,proto3,oneof" json:"board_part_number,omitempty"`
	ProductManufacturer *string                `protobuf:"bytes,6,opt,name=product_manufacturer,json=productManufacturer,proto3,oneof" json:"product_manufacturer,omitempty"`
	ProductPartNumber   *string                `protobuf:"bytes,7,opt,name=product_part_number,json=productPartNumber,proto3,oneof" json:"product_part_number,omitempty"`
	ProductSerial       *string                `protobuf:"bytes,8,opt,name=product_serial,json=productSerial,proto3,oneof" json:"product_serial,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MachineFRU) Reset() {
	*x = MachineFRU{}
	mi := &file_api_v1_boot_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineFRU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineFRU) ProtoMessage() {}

func (x *MachineFRU) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_boot_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineFRU.ProtoReflect.Descriptor instead.
func (*MachineFRU) Descriptor() ([]byte, []int) {
	return file_api_v1_boot_proto_rawDescGZIP(), []int{15}
}

func (x *MachineFRU) GetChassisPartNumber() string {
	if x != nil && x.ChassisPartNumber != nil {
		return *x.ChassisPartNumber
	}
	return ""
}

func (x *MachineFRU) GetChassisPartSerial() string {
	if x != nil && x.ChassisPartSerial != nil {
		return *x.ChassisPartSerial
	}
	return ""
}

func (x *MachineFRU) GetBoardMfg() string {
	if x != nil && x.BoardMfg != nil {
		return *x.BoardMfg
	}
	return ""
}

func (x *MachineFRU) GetBoardMfgSerial() string {
	if x != nil && x.BoardMfgSerial != nil {
		return *x.BoardMfgSerial
	}
	return ""
}

func (x *MachineFRU) GetBoardPartNumber() string {
	if x != nil && x.BoardPartNumber != nil {
		return *x.BoardPartNumber
	}
	return ""
}

func (x *MachineFRU) GetProductManufacturer() string {
	if x != nil && x.ProductManufacturer != nil {
		return *x.ProductManufacturer
	}
	return ""
}

func (x *MachineFRU) GetProductPartNumber() string {
	if x != nil && x.ProductPartNumber != nil {
		return *x.ProductPartNumber
	}
	return ""
}

func (x *MachineFRU) GetProductSerial() string {
	if x != nil && x.ProductSerial != nil {
		return *x.ProductSerial
	}
	return ""
}

type BootServiceReportRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Uuid            string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	ConsolePassword string                 `protobuf:"bytes,2,opt,name=console_password,json=consolePassword,proto3" json:"console_password,omitempty"`
	BootInfo        *BootInfo              `protobuf:"bytes,3,opt,name=boot_info,json=bootInfo,proto3" json:"boot_info,omitempty"`
	Success         bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	Message         string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BootServiceReportRequest) Reset() {
	*x = BootServiceReportRequest{}
	mi := &file_api_v1_boot_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootServiceReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootServiceReportRequest) ProtoMessage() {}

func (x *BootServiceReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_boot_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootServiceReportRequest.ProtoReflect.Descriptor instead.
func (*BootServiceReportRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_boot_proto_rawDescGZIP(), []int{16}
}

func (x *BootServiceReportRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *BootServiceReportRequest) GetConsolePassword() string {
	if x != nil {
		return x.ConsolePassword
	}
	return ""
}

func (x *BootServiceReportRequest) GetBootInfo() *BootInfo {
	if x != nil {
		return x.BootInfo
	}
	return nil
}

func (x *BootServiceReportRequest) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BootServiceReportRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BootServiceReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootServiceReportResponse) Reset() {
	*x = BootServiceReportResponse{}
	mi := &file_api_v1_boot_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootServiceReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootServiceReportResponse) ProtoMessage() {}

func (x *BootServiceReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_boot_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootServiceReportResponse.ProtoReflect.Descriptor instead.
func (*BootServiceReportResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_boot_proto_rawDescGZIP(), []int{17}
}

type BootInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageId       string                 `protobuf:"bytes,1,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	PrimaryDisk   string                 `protobuf:"bytes,2,opt,name=primary_disk,json=primaryDisk,proto3" json:"primary_disk,omitempty"`
	OsPartition   string                 `protobuf:"bytes,3,opt,name=os_partition,json=osPartition,proto3" json:"os_partition,omitempty"`
	Initrd        string                 `protobuf:"bytes,4,opt,name=initrd,proto3" json:"initrd,omitempty"`
	Cmdline       string                 `protobuf:"bytes,5,opt,name=cmdline,proto3" json:"cmdline,omitempty"`
	Kernel        string                 `protobuf:"bytes,6,opt,name=kernel,proto3" json:"kernel,omitempty"`
	BootloaderId  string                 `protobuf:"bytes,8,opt,name=bootloader_id,json=bootloaderId,proto3" json:"bootloader_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootInfo) Reset() {
	*x = BootInfo{}
	mi := &file_api_v1_boot_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootInfo) ProtoMessage() {}

func (x *BootInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_boot_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootInfo.ProtoReflect.Descriptor instead.
func (*BootInfo) Descriptor() ([]byte, []int) {
	return file_api_v1_boot_proto_rawDescGZIP(), []int{18}
}

func (x *BootInfo) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *BootInfo) GetPrimaryDisk() string {
	if x != nil {
		return x.PrimaryDisk
	}
	return ""
}

func (x *BootInfo) GetOsPartition() string {
	if x != nil {
		return x.OsPartition
	}
	return ""
}

func (x *BootInfo) GetInitrd() string {
	if x != nil {
		return x.Initrd
	}
	return ""
}

func (x *BootInfo) GetCmdline() string {
	if x != nil {
		return x.Cmdline
	}
	return ""
}

func (x *BootInfo) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

func (x *BootInfo) GetBootloaderId() string {
	if x != nil {
		return x.BootloaderId
	}
	return ""
}

type BootServiceAbortReinstallRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Uuid             string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	PrimaryDiskWiped bool                   `protobuf:"varint,2,opt,name=primary_disk_wiped,json=primaryDiskWiped,proto3" json:"primary_disk_wiped,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BootServiceAbortReinstallRequest) Reset() {
	*x = BootServiceAbortReinstallRequest{}
	mi := &file_api_v1_boot_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootServiceAbortReinstallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootServiceAbortReinstallRequest) ProtoMessage() {}

func (x *BootServiceAbortReinstallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_boot_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootServiceAbortReinstallRequest.ProtoReflect.Descriptor instead.
func (*BootServiceAbortReinstallRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_boot_proto_rawDescGZIP(), []int{19}
}

func (x *BootServiceAbortReinstallRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *BootServiceAbortReinstallRequest) GetPrimaryDiskWiped() bool {
	if x != nil {
		return x.PrimaryDiskWiped
	}
	return false
}

type BootServiceAbortReinstallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BootInfo      *BootInfo              `protobuf:"bytes,1,opt,name=boot_info,json=bootInfo,proto3" json:"boot_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootServiceAbortReinstallResponse) Reset() {
	*x = BootServiceAbortReinstallResponse{}
	mi := &file_api_v1_boot_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootServiceAbortReinstallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootServiceAbortReinstallResponse) ProtoMessage() {}

func (x *BootServiceAbortReinstallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_boot_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootServiceAbortReinstallResponse.ProtoReflect.Descriptor instead.
func (*BootServiceAbortReinstallResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_boot_proto_rawDescGZIP(), []int{20}
}

func (x *BootServiceAbortReinstallResponse) GetBootInfo() *BootInfo {
	if x != nil {
		return x.BootInfo
	}
	return nil
}

type BootServiceSuperUserPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootServiceSuperUserPasswordRequest) Reset() {
	*x = BootServiceSuperUserPasswordRequest{}
	mi := &file_api_v1_boot_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootServiceSuperUserPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootServiceSuperUserPasswordRequest) ProtoMessage() {}

func (x *BootServiceSuperUserPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_boot_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootServiceSuperUserPasswordRequest.ProtoReflect.Descriptor instead.
func (*BootServiceSuperUserPasswordRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_boot_proto_rawDescGZIP(), []int{21}
}

type BootServiceSuperUserPasswordResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	FeatureDisabled   bool                   `protobuf:"varint,1,opt,name=feature_disabled,json=featureDisabled,proto3" json:"feature_disabled,omitempty"`
	SuperUserPassword string                 `protobuf:"bytes,2,opt,name=super_user_password,json=superUserPassword,proto3" json:"super_user_password,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BootServiceSuperUserPasswordResponse) Reset() {
	*x = BootServiceSuperUserPasswordResponse{}
	mi := &file_api_v1_boot_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootServiceSuperUserPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootServiceSuperUserPasswordResponse) ProtoMessage() {}

func (x *BootServiceSuperUserPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_boot_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootServiceSuperUserPasswordResponse.ProtoReflect.Descriptor instead.
func (*BootServiceSuperUserPasswordResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_boot_proto_rawDescGZIP(), []int{22}
}

func (x *BootServiceSuperUserPasswordResponse) GetFeatureDisabled() bool {
	if x != nil {
		return x.FeatureDisabled
	}
	return false
}

func (x *BootServiceSuperUserPasswordResponse) GetSuperUserPassword() string {
	if x != nil {
		return x.SuperUserPassword
	}
	return ""
}

var File_api_v1_boot_proto protoreflect.FileDescriptor

const file_api_v1_boot_proto_rawDesc = "" +
	"\n" +
	"\x11api/v1/boot.proto\x12\x06api.v1\",\n" +
	"\x16BootServiceDhcpRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\x19\n" +
	"\x17BootServiceDhcpResponse\"M\n" +
	"\x16BootServiceBootRequest\x12\x10\n" +
	"\x03mac\x18\x01 \x01(\tR\x03mac\x12!\n" +
	"\fpartition_id\x18\x02 \x01(\tR\vpartitionId\"\x82\x01\n" +
	"\x17BootServiceBootResponse\x12\x16\n" +
	"\x06kernel\x18\x01 \x01(\tR\x06kernel\x12$\n" +
	"\x0einit_ram_disks\x18\x02 \x03(\tR\finitRamDisks\x12\x1d\n" +
	"\acmdline\x18\x03 \x01(\tH\x00R\acmdline\x88\x01\x01B\n" +
	"\n" +
	"\b_cmdline\"\xa0\x02\n" +
	"\x1aBootServiceRegisterRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x123\n" +
	"\bhardware\x18\x02 \x01(\v2\x17.api.v1.MachineHardwareR\bhardware\x12'\n" +
	"\x04bios\x18\x03 \x01(\v2\x13.api.v1.MachineBIOSR\x04bios\x12'\n" +
	"\x04ipmi\x18\x04 \x01(\v2\x13.api.v1.MachineIPMIR\x04ipmi\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x120\n" +
	"\x14metal_hammer_version\x18\x06 \x01(\tR\x12metalHammerVersion\x12!\n" +
	"\fpartition_id\x18\a \x01(\tR\vpartitionId\"h\n" +
	"\x1bBootServiceRegisterResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04size\x18\x02 \x01(\tR\x04size\x12!\n" +
	"\fpartition_id\x18\x03 \x01(\tR\vpartitionId\"7\n" +
	"\x16BootServiceWaitRequest\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\"\x19\n" +
	"\x17BootServiceWaitResponse\"\xd3\x01\n" +
	"\x0fMachineHardware\x12\x16\n" +
	"\x06memory\x18\x01 \x01(\x04R\x06memory\x120\n" +
	"\x05disks\x18\x03 \x03(\v2\x1a.api.v1.MachineBlockDeviceR\x05disks\x12&\n" +
	"\x04nics\x18\x04 \x03(\v2\x12.api.v1.MachineNicR\x04nics\x12&\n" +
	"\x04cpus\x18\x05 \x03(\v2\x12.api.v1.MachineCPUR\x04cpus\x12&\n" +
	"\x04gpus\x18\x06 \x03(\v2\x12.api.v1.MachineGPUR\x04gpus\"j\n" +
	"\n" +
	"MachineCPU\x12\x16\n" +
	"\x06vendor\x18\x01 \x01(\tR\x06vendor\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x14\n" +
	"\x05cores\x18\x03 \x01(\rR\x05cores\x12\x18\n" +
	"\athreads\x18\x04 \x01(\rR\athreads\":\n" +
	"\n" +
	"MachineGPU\x12\x16\n" +
	"\x06vendor\x18\x01 \x01(\tR\x06vendor\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\"\xa0\x01\n" +
	"\n" +
	"MachineNic\x12\x10\n" +
	"\x03mac\x18\x01 \x01(\tR\x03mac\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x120\n" +
	"\tneighbors\x18\x03 \x03(\v2\x12.api.v1.MachineNicR\tneighbors\x12\x1a\n" +
	"\bhostname\x18\x04 \x01(\tR\bhostname\x12\x1e\n" +
	"\n" +
	"identifier\x18\x05 \x01(\tR\n" +
	"identifier\"<\n" +
	"\x12MachineBlockDevice\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\"S\n" +
	"\vMachineBIOS\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06vendor\x18\x02 \x01(\tR\x06vendor\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\"\xef\x01\n" +
	"\vMachineIPMI\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x10\n" +
	"\x03mac\x18\x02 \x01(\tR\x03mac\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x1c\n" +
	"\tinterface\x18\x05 \x01(\tR\tinterface\x12$\n" +
	"\x03fru\x18\x06 \x01(\v2\x12.api.v1.MachineFRUR\x03fru\x12\x1f\n" +
	"\vbmc_version\x18\a \x01(\tR\n" +
	"bmcVersion\x12\x1f\n" +
	"\vpower_state\x18\b \x01(\tR\n" +
	"powerState\"\xbe\x04\n" +
	"\n" +
	"MachineFRU\x123\n" +
	"\x13chassis_part_number\x18\x01 \x01(\tH\x00R\x11chassisPartNumber\x88\x01\x01\x123\n" +
	"\x13chassis_part_serial\x18\x02 \x01(\tH\x01R\x11chassisPartSerial\x88\x01\x01\x12 \n" +
	"\tboard_mfg\x18\x03 \x01(\tH\x02R\bboardMfg\x88\x01\x01\x12-\n" +
	"\x10board_mfg_serial\x18\x04 \x01(\tH\x03R\x0eboardMfgSerial\x88\x01\x01\x12/\n" +
	"\x11board_part_number\x18\x05 \x01(\tH\x04R\x0fboardPartNumber\x88\x01\x01\x126\n" +
	"\x14product_manufacturer\x18\x06 \x01(\tH\x05R\x13productManufacturer\x88\x01\x01\x123\n" +
	"\x13product_part_number\x18\a \x01(\tH\x06R\x11productPartNumber\x88\x01\x01\x12*\n" +
	"\x0eproduct_serial\x18\b \x01(\tH\aR\rproductSerial\x88\x01\x01B\x16\n" +
	"\x14_chassis_part_numberB\x16\n" +
	"\x14_chassis_part_serialB\f\n" +
	"\n" +
	"_board_mfgB\x13\n" +
	"\x11_board_mfg_serialB\x14\n" +
	"\x12_board_part_numberB\x17\n" +
	"\x15_product_manufacturerB\x16\n" +
	"\x14_product_part_numberB\x11\n" +
	"\x0f_product_serial\"\xbc\x01\n" +
	"\x18BootServiceReportRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12)\n" +
	"\x10console_password\x18\x02 \x01(\tR\x0fconsolePassword\x12-\n" +
	"\tboot_info\x18\x03 \x01(\v2\x10.api.v1.BootInfoR\bbootInfo\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"\x1b\n" +
	"\x19BootServiceReportResponse\"\xda\x01\n" +
	"\bBootInfo\x12\x19\n" +
	"\bimage_id\x18\x01 \x01(\tR\aimageId\x12!\n" +
	"\fprimary_disk\x18\x02 \x01(\tR\vprimaryDisk\x12!\n" +
	"\fos_partition\x18\x03 \x01(\tR\vosPartition\x12\x16\n" +
	"\x06initrd\x18\x04 \x01(\tR\x06initrd\x12\x18\n" +
	"\acmdline\x18\x05 \x01(\tR\acmdline\x12\x16\n" +
	"\x06kernel\x18\x06 \x01(\tR\x06kernel\x12#\n" +
	"\rbootloader_id\x18\b \x01(\tR\fbootloaderId\"d\n" +
	" BootServiceAbortReinstallRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12,\n" +
	"\x12primary_disk_wiped\x18\x02 \x01(\bR\x10primaryDiskWiped\"R\n" +
	"!BootServiceAbortReinstallResponse\x12-\n" +
	"\tboot_info\x18\x01 \x01(\v2\x10.api.v1.BootInfoR\bbootInfo\"%\n" +
	"#BootServiceSuperUserPasswordRequest\"\x81\x01\n" +
	"$BootServiceSuperUserPasswordResponse\x12)\n" +
	"\x10feature_disabled\x18\x01 \x01(\bR\x0ffeatureDisabled\x12.\n" +
	"\x13super_user_password\x18\x02 \x01(\tR\x11superUserPassword2\xef\x04\n" +
	"\vBootService\x12I\n" +
	"\x04Dhcp\x12\x1e.api.v1.BootServiceDhcpRequest\x1a\x1f.api.v1.BootServiceDhcpResponse\"\x00\x12I\n" +
	"\x04Boot\x12\x1e.api.v1.BootServiceBootRequest\x1a\x1f.api.v1.BootServiceBootResponse\"\x00\x12n\n" +
	"\x11SuperUserPassword\x12+.api.v1.BootServiceSuperUserPasswordRequest\x1a,.api.v1.BootServiceSuperUserPasswordResponse\x12U\n" +
	"\bRegister\x12\".api.v1.BootServiceRegisterRequest\x1a#.api.v1.BootServiceRegisterResponse\"\x00\x12I\n" +
	"\x04Wait\x12\x1e.api.v1.BootServiceWaitRequest\x1a\x1f.api.v1.BootServiceWaitResponse0\x01\x12O\n" +
	"\x06Report\x12 .api.v1.BootServiceReportRequest\x1a!.api.v1.BootServiceReportResponse\"\x00\x12g\n" +
	"\x0eAbortReinstall\x12(.api.v1.BootServiceAbortReinstallRequest\x1a).api.v1.BootServiceAbortReinstallResponse\"\x00B\x06Z\x04./v1b\x06proto3"

var (
	file_api_v1_boot_proto_rawDescOnce sync.Once
	file_api_v1_boot_proto_rawDescData []byte
)

func file_api_v1_boot_proto_rawDescGZIP() []byte {
	file_api_v1_boot_proto_rawDescOnce.Do(func() {
		file_api_v1_boot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_boot_proto_rawDesc), len(file_api_v1_boot_proto_rawDesc)))
	})
	return file_api_v1_boot_proto_rawDescData
}

var file_api_v1_boot_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_api_v1_boot_proto_goTypes = []any{
	(*BootServiceDhcpRequest)(nil),               // 0: api.v1.BootServiceDhcpRequest
	(*BootServiceDhcpResponse)(nil),              // 1: api.v1.BootServiceDhcpResponse
	(*BootServiceBootRequest)(nil),               // 2: api.v1.BootServiceBootRequest
	(*BootServiceBootResponse)(nil),              // 3: api.v1.BootServiceBootResponse
	(*BootServiceRegisterRequest)(nil),           // 4: api.v1.BootServiceRegisterRequest
	(*BootServiceRegisterResponse)(nil),          // 5: api.v1.BootServiceRegisterResponse
	(*BootServiceWaitRequest)(nil),               // 6: api.v1.BootServiceWaitRequest
	(*BootServiceWaitResponse)(nil),              // 7: api.v1.BootServiceWaitResponse
	(*MachineHardware)(nil),                      // 8: api.v1.MachineHardware
	(*MachineCPU)(nil),                           // 9: api.v1.MachineCPU
	(*MachineGPU)(nil),                           // 10: api.v1.MachineGPU
	(*MachineNic)(nil),                           // 11: api.v1.MachineNic
	(*MachineBlockDevice)(nil),                   // 12: api.v1.MachineBlockDevice
	(*MachineBIOS)(nil),                          // 13: api.v1.MachineBIOS
	(*MachineIPMI)(nil),                          // 14: api.v1.MachineIPMI
	(*MachineFRU)(nil),                           // 15: api.v1.MachineFRU
	(*BootServiceReportRequest)(nil),             // 16: api.v1.BootServiceReportRequest
	(*BootServiceReportResponse)(nil),            // 17: api.v1.BootServiceReportResponse
	(*BootInfo)(nil),                             // 18: api.v1.BootInfo
	(*BootServiceAbortReinstallRequest)(nil),     // 19: api.v1.BootServiceAbortReinstallRequest
	(*BootServiceAbortReinstallResponse)(nil),    // 20: api.v1.BootServiceAbortReinstallResponse
	(*BootServiceSuperUserPasswordRequest)(nil),  // 21: api.v1.BootServiceSuperUserPasswordRequest
	(*BootServiceSuperUserPasswordResponse)(nil), // 22: api.v1.BootServiceSuperUserPasswordResponse
}
var file_api_v1_boot_proto_depIdxs = []int32{
	8,  // 0: api.v1.BootServiceRegisterRequest.hardware:type_name -> api.v1.MachineHardware
	13, // 1: api.v1.BootServiceRegisterRequest.bios:type_name -> api.v1.MachineBIOS
	14, // 2: api.v1.BootServiceRegisterRequest.ipmi:type_name -> api.v1.MachineIPMI
	12, // 3: api.v1.MachineHardware.disks:type_name -> api.v1.MachineBlockDevice
	11, // 4: api.v1.MachineHardware.nics:type_name -> api.v1.MachineNic
	9,  // 5: api.v1.MachineHardware.cpus:type_name -> api.v1.MachineCPU
	10, // 6: api.v1.MachineHardware.gpus:type_name -> api.v1.MachineGPU
	11, // 7: api.v1.MachineNic.neighbors:type_name -> api.v1.MachineNic
	15, // 8: api.v1.MachineIPMI.fru:type_name -> api.v1.MachineFRU
	18, // 9: api.v1.BootServiceReportRequest.boot_info:type_name -> api.v1.BootInfo
	18, // 10: api.v1.BootServiceAbortReinstallResponse.boot_info:type_name -> api.v1.BootInfo
	0,  // 11: api.v1.BootService.Dhcp:input_type -> api.v1.BootServiceDhcpRequest
	2,  // 12: api.v1.BootService.Boot:input_type -> api.v1.BootServiceBootRequest
	21, // 13: api.v1.BootService.SuperUserPassword:input_type -> api.v1.BootServiceSuperUserPasswordRequest
	4,  // 14: api.v1.BootService.Register:input_type -> api.v1.BootServiceRegisterRequest
	6,  // 15: api.v1.BootService.Wait:input_type -> api.v1.BootServiceWaitRequest
	16, // 16: api.v1.BootService.Report:input_type -> api.v1.BootServiceReportRequest
	19, // 17: api.v1.BootService.AbortReinstall:input_type -> api.v1.BootServiceAbortReinstallRequest
	1,  // 18: api.v1.BootService.Dhcp:output_type -> api.v1.BootServiceDhcpResponse
	3,  // 19: api.v1.BootService.Boot:output_type -> api.v1.BootServiceBootResponse
	22, // 20: api.v1.BootService.SuperUserPassword:output_type -> api.v1.BootServiceSuperUserPasswordResponse
	5,  // 21: api.v1.BootService.Register:output_type -> api.v1.BootServiceRegisterResponse
	7,  // 22: api.v1.BootService.Wait:output_type -> api.v1.BootServiceWaitResponse
	17, // 23: api.v1.BootService.Report:output_type -> api.v1.BootServiceReportResponse
	20, // 24: api.v1.BootService.AbortReinstall:output_type -> api.v1.BootServiceAbortReinstallResponse
	18, // [18:25] is the sub-list for method output_type
	11, // [11:18] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_api_v1_boot_proto_init() }
func file_api_v1_boot_proto_init() {
	if File_api_v1_boot_proto != nil {
		return
	}
	file_api_v1_boot_proto_msgTypes[3].OneofWrappers = []any{}
	file_api_v1_boot_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_boot_proto_rawDesc), len(file_api_v1_boot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_boot_proto_goTypes,
		DependencyIndexes: file_api_v1_boot_proto_depIdxs,
		MessageInfos:      file_api_v1_boot_proto_msgTypes,
	}.Build()
	File_api_v1_boot_proto = out.File
	file_api_v1_boot_proto_goTypes = nil
	file_api_v1_boot_proto_depIdxs = nil
}
