// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/v1/event.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventServiceSendRequest struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Events        map[string]*MachineProvisioningEvent `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventServiceSendRequest) Reset() {
	*x = EventServiceSendRequest{}
	mi := &file_api_v1_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventServiceSendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventServiceSendRequest) ProtoMessage() {}

func (x *EventServiceSendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventServiceSendRequest.ProtoReflect.Descriptor instead.
func (*EventServiceSendRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{0}
}

func (x *EventServiceSendRequest) GetEvents() map[string]*MachineProvisioningEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type EventServiceSendResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// number of events stored
	Events uint64 `protobuf:"varint,1,opt,name=events,proto3" json:"events,omitempty"`
	// slice of machineIDs for which event was not published
	Failed        []string `protobuf:"bytes,2,rep,name=failed,proto3" json:"failed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventServiceSendResponse) Reset() {
	*x = EventServiceSendResponse{}
	mi := &file_api_v1_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventServiceSendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventServiceSendResponse) ProtoMessage() {}

func (x *EventServiceSendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventServiceSendResponse.ProtoReflect.Descriptor instead.
func (*EventServiceSendResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{1}
}

func (x *EventServiceSendResponse) GetEvents() uint64 {
	if x != nil {
		return x.Events
	}
	return 0
}

func (x *EventServiceSendResponse) GetFailed() []string {
	if x != nil {
		return x.Failed
	}
	return nil
}

type MachineProvisioningEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// timestamp when the event occurred
	Time *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	// the event type
	// must be one of metal.ProvisioningEventType, otherwise event will be skipped
	// TODO should be migrated to be an enum
	Event string `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	// an additional message describing the event more detailed
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineProvisioningEvent) Reset() {
	*x = MachineProvisioningEvent{}
	mi := &file_api_v1_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineProvisioningEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineProvisioningEvent) ProtoMessage() {}

func (x *MachineProvisioningEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineProvisioningEvent.ProtoReflect.Descriptor instead.
func (*MachineProvisioningEvent) Descriptor() ([]byte, []int) {
	return file_api_v1_event_proto_rawDescGZIP(), []int{2}
}

func (x *MachineProvisioningEvent) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *MachineProvisioningEvent) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *MachineProvisioningEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_v1_event_proto protoreflect.FileDescriptor

const file_api_v1_event_proto_rawDesc = "" +
	"\n" +
	"\x12api/v1/event.proto\x12\x06api.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbb\x01\n" +
	"\x17EventServiceSendRequest\x12C\n" +
	"\x06events\x18\x01 \x03(\v2+.api.v1.EventServiceSendRequest.EventsEntryR\x06events\x1a[\n" +
	"\vEventsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\x05value\x18\x02 \x01(\v2 .api.v1.MachineProvisioningEventR\x05value:\x028\x01\"J\n" +
	"\x18EventServiceSendResponse\x12\x16\n" +
	"\x06events\x18\x01 \x01(\x04R\x06events\x12\x16\n" +
	"\x06failed\x18\x02 \x03(\tR\x06failed\"z\n" +
	"\x18MachineProvisioningEvent\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x14\n" +
	"\x05event\x18\x02 \x01(\tR\x05event\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2[\n" +
	"\fEventService\x12K\n" +
	"\x04Send\x12\x1f.api.v1.EventServiceSendRequest\x1a .api.v1.EventServiceSendResponse\"\x00B\x06Z\x04./v1b\x06proto3"

var (
	file_api_v1_event_proto_rawDescOnce sync.Once
	file_api_v1_event_proto_rawDescData []byte
)

func file_api_v1_event_proto_rawDescGZIP() []byte {
	file_api_v1_event_proto_rawDescOnce.Do(func() {
		file_api_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_event_proto_rawDesc), len(file_api_v1_event_proto_rawDesc)))
	})
	return file_api_v1_event_proto_rawDescData
}

var file_api_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_v1_event_proto_goTypes = []any{
	(*EventServiceSendRequest)(nil),  // 0: api.v1.EventServiceSendRequest
	(*EventServiceSendResponse)(nil), // 1: api.v1.EventServiceSendResponse
	(*MachineProvisioningEvent)(nil), // 2: api.v1.MachineProvisioningEvent
	nil,                              // 3: api.v1.EventServiceSendRequest.EventsEntry
	(*timestamppb.Timestamp)(nil),    // 4: google.protobuf.Timestamp
}
var file_api_v1_event_proto_depIdxs = []int32{
	3, // 0: api.v1.EventServiceSendRequest.events:type_name -> api.v1.EventServiceSendRequest.EventsEntry
	4, // 1: api.v1.MachineProvisioningEvent.time:type_name -> google.protobuf.Timestamp
	2, // 2: api.v1.EventServiceSendRequest.EventsEntry.value:type_name -> api.v1.MachineProvisioningEvent
	0, // 3: api.v1.EventService.Send:input_type -> api.v1.EventServiceSendRequest
	1, // 4: api.v1.EventService.Send:output_type -> api.v1.EventServiceSendResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_v1_event_proto_init() }
func file_api_v1_event_proto_init() {
	if File_api_v1_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_event_proto_rawDesc), len(file_api_v1_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_event_proto_goTypes,
		DependencyIndexes: file_api_v1_event_proto_depIdxs,
		MessageInfos:      file_api_v1_event_proto_msgTypes,
	}.Build()
	File_api_v1_event_proto = out.File
	file_api_v1_event_proto_goTypes = nil
	file_api_v1_event_proto_depIdxs = nil
}
