// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.20.1
// 	protoc        v3.11.4
// source: api/v1/supwd.proto

package v1

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SupermetalPasswordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PartitionID string `protobuf:"bytes,1,opt,name=partitionID,proto3" json:"partitionID,omitempty"`
}

func (x *SupermetalPasswordRequest) Reset() {
	*x = SupermetalPasswordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_supwd_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SupermetalPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupermetalPasswordRequest) ProtoMessage() {}

func (x *SupermetalPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_supwd_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupermetalPasswordRequest.ProtoReflect.Descriptor instead.
func (*SupermetalPasswordRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_supwd_proto_rawDescGZIP(), []int{0}
}

func (x *SupermetalPasswordRequest) GetPartitionID() string {
	if x != nil {
		return x.PartitionID
	}
	return ""
}

type SupermetalPasswordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SupermetalPassword string `protobuf:"bytes,1,opt,name=supermetalPassword,proto3" json:"supermetalPassword,omitempty"`
}

func (x *SupermetalPasswordResponse) Reset() {
	*x = SupermetalPasswordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_supwd_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SupermetalPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupermetalPasswordResponse) ProtoMessage() {}

func (x *SupermetalPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_supwd_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupermetalPasswordResponse.ProtoReflect.Descriptor instead.
func (*SupermetalPasswordResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_supwd_proto_rawDescGZIP(), []int{1}
}

func (x *SupermetalPasswordResponse) GetSupermetalPassword() string {
	if x != nil {
		return x.SupermetalPassword
	}
	return ""
}

var File_api_v1_supwd_proto protoreflect.FileDescriptor

var file_api_v1_supwd_proto_rawDesc = []byte{
	0x0a, 0x12, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x75, 0x70, 0x77, 0x64, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76, 0x31, 0x22, 0x3d, 0x0a, 0x19, 0x53, 0x75, 0x70, 0x65,
	0x72, 0x6d, 0x65, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x61, 0x72, 0x74,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x22, 0x4c, 0x0a, 0x1a, 0x53, 0x75, 0x70, 0x65, 0x72,
	0x6d, 0x65, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x12, 0x73, 0x75, 0x70, 0x65, 0x72, 0x6d, 0x65,
	0x74, 0x61, 0x6c, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x12, 0x73, 0x75, 0x70, 0x65, 0x72, 0x6d, 0x65, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x32, 0x6e, 0x0a, 0x12, 0x53, 0x75, 0x70, 0x65, 0x72, 0x6d, 0x65,
	0x74, 0x61, 0x6c, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x58, 0x0a, 0x17, 0x46,
	0x65, 0x74, 0x63, 0x68, 0x53, 0x75, 0x70, 0x65, 0x72, 0x6d, 0x65, 0x74, 0x61, 0x6c, 0x50, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1d, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x75, 0x70, 0x65,
	0x72, 0x6d, 0x65, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x75, 0x70, 0x65, 0x72,
	0x6d, 0x65, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x08, 0x5a, 0x06, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_supwd_proto_rawDescOnce sync.Once
	file_api_v1_supwd_proto_rawDescData = file_api_v1_supwd_proto_rawDesc
)

func file_api_v1_supwd_proto_rawDescGZIP() []byte {
	file_api_v1_supwd_proto_rawDescOnce.Do(func() {
		file_api_v1_supwd_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_supwd_proto_rawDescData)
	})
	return file_api_v1_supwd_proto_rawDescData
}

var file_api_v1_supwd_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_v1_supwd_proto_goTypes = []interface{}{
	(*SupermetalPasswordRequest)(nil),  // 0: v1.SupermetalPasswordRequest
	(*SupermetalPasswordResponse)(nil), // 1: v1.SupermetalPasswordResponse
}
var file_api_v1_supwd_proto_depIdxs = []int32{
	0, // 0: v1.SupermetalPassword.FetchSupermetalPassword:input_type -> v1.SupermetalPasswordRequest
	1, // 1: v1.SupermetalPassword.FetchSupermetalPassword:output_type -> v1.SupermetalPasswordResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_v1_supwd_proto_init() }
func file_api_v1_supwd_proto_init() {
	if File_api_v1_supwd_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_supwd_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SupermetalPasswordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_supwd_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SupermetalPasswordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_supwd_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_supwd_proto_goTypes,
		DependencyIndexes: file_api_v1_supwd_proto_depIdxs,
		MessageInfos:      file_api_v1_supwd_proto_msgTypes,
	}.Build()
	File_api_v1_supwd_proto = out.File
	file_api_v1_supwd_proto_rawDesc = nil
	file_api_v1_supwd_proto_goTypes = nil
	file_api_v1_supwd_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SupermetalPasswordClient is the client API for SupermetalPassword service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SupermetalPasswordClient interface {
	FetchSupermetalPassword(ctx context.Context, in *SupermetalPasswordRequest, opts ...grpc.CallOption) (*SupermetalPasswordResponse, error)
}

type supermetalPasswordClient struct {
	cc grpc.ClientConnInterface
}

func NewSupermetalPasswordClient(cc grpc.ClientConnInterface) SupermetalPasswordClient {
	return &supermetalPasswordClient{cc}
}

func (c *supermetalPasswordClient) FetchSupermetalPassword(ctx context.Context, in *SupermetalPasswordRequest, opts ...grpc.CallOption) (*SupermetalPasswordResponse, error) {
	out := new(SupermetalPasswordResponse)
	err := c.cc.Invoke(ctx, "/v1.SupermetalPassword/FetchSupermetalPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SupermetalPasswordServer is the server API for SupermetalPassword service.
type SupermetalPasswordServer interface {
	FetchSupermetalPassword(context.Context, *SupermetalPasswordRequest) (*SupermetalPasswordResponse, error)
}

// UnimplementedSupermetalPasswordServer can be embedded to have forward compatible implementations.
type UnimplementedSupermetalPasswordServer struct {
}

func (*UnimplementedSupermetalPasswordServer) FetchSupermetalPassword(context.Context, *SupermetalPasswordRequest) (*SupermetalPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchSupermetalPassword not implemented")
}

func RegisterSupermetalPasswordServer(s *grpc.Server, srv SupermetalPasswordServer) {
	s.RegisterService(&_SupermetalPassword_serviceDesc, srv)
}

func _SupermetalPassword_FetchSupermetalPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SupermetalPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupermetalPasswordServer).FetchSupermetalPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.SupermetalPassword/FetchSupermetalPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupermetalPasswordServer).FetchSupermetalPassword(ctx, req.(*SupermetalPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SupermetalPassword_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.SupermetalPassword",
	HandlerType: (*SupermetalPasswordServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchSupermetalPassword",
			Handler:    _SupermetalPassword_FetchSupermetalPassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/supwd.proto",
}
