// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: api/v1/switch.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SwitchServicePortUpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// switch_id is the identifier of the switch
	SwitchId string `protobuf:"bytes,1,opt,name=switch_id,json=switchId,proto3" json:"switch_id,omitempty"`
	// port_identifier is the identifier of the switch port to take up
	PortIdentifier string `protobuf:"bytes,2,opt,name=port_identifier,json=portIdentifier,proto3" json:"port_identifier,omitempty"`
}

func (x *SwitchServicePortUpRequest) Reset() {
	*x = SwitchServicePortUpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_switch_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SwitchServicePortUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchServicePortUpRequest) ProtoMessage() {}

func (x *SwitchServicePortUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_switch_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchServicePortUpRequest.ProtoReflect.Descriptor instead.
func (*SwitchServicePortUpRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_switch_proto_rawDescGZIP(), []int{0}
}

func (x *SwitchServicePortUpRequest) GetSwitchId() string {
	if x != nil {
		return x.SwitchId
	}
	return ""
}

func (x *SwitchServicePortUpRequest) GetPortIdentifier() string {
	if x != nil {
		return x.PortIdentifier
	}
	return ""
}

type SwitchServicePortDownRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// switch_id is the identifier of the switch
	SwitchId string `protobuf:"bytes,1,opt,name=switch_id,json=switchId,proto3" json:"switch_id,omitempty"`
	// identifier is the identifier of the switch port to take down
	PortIdentifier string `protobuf:"bytes,2,opt,name=port_identifier,json=portIdentifier,proto3" json:"port_identifier,omitempty"`
}

func (x *SwitchServicePortDownRequest) Reset() {
	*x = SwitchServicePortDownRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_switch_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SwitchServicePortDownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchServicePortDownRequest) ProtoMessage() {}

func (x *SwitchServicePortDownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_switch_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchServicePortDownRequest.ProtoReflect.Descriptor instead.
func (*SwitchServicePortDownRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_switch_proto_rawDescGZIP(), []int{1}
}

func (x *SwitchServicePortDownRequest) GetSwitchId() string {
	if x != nil {
		return x.SwitchId
	}
	return ""
}

func (x *SwitchServicePortDownRequest) GetPortIdentifier() string {
	if x != nil {
		return x.PortIdentifier
	}
	return ""
}

type SwitchServicePortUpResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SwitchServicePortUpResponse) Reset() {
	*x = SwitchServicePortUpResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_switch_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SwitchServicePortUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchServicePortUpResponse) ProtoMessage() {}

func (x *SwitchServicePortUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_switch_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchServicePortUpResponse.ProtoReflect.Descriptor instead.
func (*SwitchServicePortUpResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_switch_proto_rawDescGZIP(), []int{2}
}

type SwitchServicePortDownResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SwitchServicePortDownResponse) Reset() {
	*x = SwitchServicePortDownResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_switch_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SwitchServicePortDownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchServicePortDownResponse) ProtoMessage() {}

func (x *SwitchServicePortDownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_switch_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchServicePortDownResponse.ProtoReflect.Descriptor instead.
func (*SwitchServicePortDownResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_switch_proto_rawDescGZIP(), []int{3}
}

var File_api_v1_switch_proto protoreflect.FileDescriptor

var file_api_v1_switch_proto_rawDesc = []byte{
	0x0a, 0x13, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x22, 0x62, 0x0a,
	0x1a, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x6f,
	0x72, 0x74, 0x55, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73,
	0x77, 0x69, 0x74, 0x63, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x70, 0x6f, 0x72, 0x74,
	0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x70, 0x6f, 0x72, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x22, 0x64, 0x0a, 0x1c, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x50, 0x6f, 0x72, 0x74, 0x44, 0x6f, 0x77, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x49, 0x64, 0x12, 0x27,
	0x0a, 0x0f, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x6f, 0x72, 0x74, 0x49, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x22, 0x1d, 0x0a, 0x1b, 0x53, 0x77, 0x69, 0x74, 0x63,
	0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x6f, 0x72, 0x74, 0x55, 0x70, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1f, 0x0a, 0x1d, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x6f, 0x72, 0x74, 0x44, 0x6f, 0x77, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xbf, 0x01, 0x0a, 0x0d, 0x53, 0x77, 0x69, 0x74,
	0x63, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x53, 0x0a, 0x06, 0x50, 0x6f, 0x72,
	0x74, 0x55, 0x70, 0x12, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x77, 0x69,
	0x74, 0x63, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x6f, 0x72, 0x74, 0x55, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x6f,
	0x72, 0x74, 0x55, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x59,
	0x0a, 0x08, 0x50, 0x6f, 0x72, 0x74, 0x44, 0x6f, 0x77, 0x6e, 0x12, 0x24, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x2e, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x50, 0x6f, 0x72, 0x74, 0x44, 0x6f, 0x77, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x25, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x6f, 0x72, 0x74, 0x44, 0x6f, 0x77, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x76,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_switch_proto_rawDescOnce sync.Once
	file_api_v1_switch_proto_rawDescData = file_api_v1_switch_proto_rawDesc
)

func file_api_v1_switch_proto_rawDescGZIP() []byte {
	file_api_v1_switch_proto_rawDescOnce.Do(func() {
		file_api_v1_switch_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_switch_proto_rawDescData)
	})
	return file_api_v1_switch_proto_rawDescData
}

var file_api_v1_switch_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_v1_switch_proto_goTypes = []interface{}{
	(*SwitchServicePortUpRequest)(nil),    // 0: api.v1.SwitchServicePortUpRequest
	(*SwitchServicePortDownRequest)(nil),  // 1: api.v1.SwitchServicePortDownRequest
	(*SwitchServicePortUpResponse)(nil),   // 2: api.v1.SwitchServicePortUpResponse
	(*SwitchServicePortDownResponse)(nil), // 3: api.v1.SwitchServicePortDownResponse
}
var file_api_v1_switch_proto_depIdxs = []int32{
	0, // 0: api.v1.SwitchService.PortUp:input_type -> api.v1.SwitchServicePortUpRequest
	1, // 1: api.v1.SwitchService.PortDown:input_type -> api.v1.SwitchServicePortDownRequest
	2, // 2: api.v1.SwitchService.PortUp:output_type -> api.v1.SwitchServicePortUpResponse
	3, // 3: api.v1.SwitchService.PortDown:output_type -> api.v1.SwitchServicePortDownResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_v1_switch_proto_init() }
func file_api_v1_switch_proto_init() {
	if File_api_v1_switch_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_v1_switch_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SwitchServicePortUpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_switch_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SwitchServicePortDownRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_switch_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SwitchServicePortUpResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_switch_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SwitchServicePortDownResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_switch_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_switch_proto_goTypes,
		DependencyIndexes: file_api_v1_switch_proto_depIdxs,
		MessageInfos:      file_api_v1_switch_proto_msgTypes,
	}.Build()
	File_api_v1_switch_proto = out.File
	file_api_v1_switch_proto_rawDesc = nil
	file_api_v1_switch_proto_goTypes = nil
	file_api_v1_switch_proto_depIdxs = nil
}
