@baseurl = {{scheme}}://{{host}}/v1/machine
@firewallbaseurl = {{scheme}}://{{host}}/v1/firewall

### register a firewall
# @name register
POST {{baseurl}}/register
Authorization: Metal-Admin bfe5650d0149046959e7e49105134877906ebd6e1be0136dd6c51cb095d4ea8d
X-Date: 1985-04-12T23:20:50.52Z
Content-Type: application/json

{
  "partitionid": "vagrant-lab",
  "rackid": "Vagrant Rack 1",
  "hardware": {
    "cpu_cores": 1,
    "disks": [
      {
        "name": "sda",
        "size": 2147483648
      }
    ],
    "memory": 536870912,
    "nics": [
      {
        "features": [
        ],
        "mac": "aa:aa:aa:aa:aa:aa",
        "name": "eth0",
        "vendor": "Dell",
        "neighbors": [
        	{
        		"mac":"11:11:11:11:11:11",
        		"name":"switch"
        	}
        ]
      },
      {
        "features": [
        ],
        "mac": "00:00:00:00:00:00",
        "name": "lo",
        "vendor": "Dell"
      }
    ]
  },
  "uuid": "ae671b8b-a158-52c2-8c22-985ca0503873"
}

### wait for a machine
# @name wait
GET {{baseurl}}/ae671b8b-a158-52c2-8c22-985ca0503873/wait
Authorization: Metal-Admin 8d7b8a807d368b716ce7d712266b680edb77ff70d050be30e0bbf2e50e189b2b
X-Date: 1985-04-12T23:20:50.52Z

### allocate a firewall
# @name allocate
POST {{firewallbaseurl}}/allocate
Content-Type: application/json
Authorization: Metal-Admin bfe5650d0149046959e7e49105134877906ebd6e1be0136dd6c51cb095d4ea8d
X-Date: 1985-04-12T23:20:50.52Z

{
  "description": "My first metal host",
  "partitionid": "vagrant-lab",
  "hostname": "metal-test-1",
  "imageid": "ubuntu-18.10-firewall",
  "name": "Metal Host 1",
  "projectid": "devops",
  "tenant": "dkb",
  "sizeid": "v1-small-x86",
  "ssh_pub_keys": [],
  "networks": [
    {"networkid": "internet-vagrant-lab"}
  ],
  "ha": false,
  "ips": []
}

### free a machine
# @name free
DELETE  {{baseurl}}/ae671b8b-a158-52c2-8c22-985ca0503873/free
Authorization: Metal-Admin 60d4480107818d260233f835ff91ec85df194a2300b290e8aba4449246919d81
X-Date: 1985-04-12T23:20:50.52Z

### get a firewall
# @name get
GET {{firewallbaseurl}}/ae671b8b-a158-52c2-8c22-985ca0503873
Authorization: Metal-Admin 8d7b8a807d368b716ce7d712266b680edb77ff70d050be30e0bbf2e50e189b2b
X-Date: 1985-04-12T23:20:50.52Z

### list firewalls
# @name list
GET {{firewallbaseurl}}/
Authorization: Metal-Admin 8d7b8a807d368b716ce7d712266b680edb77ff70d050be30e0bbf2e50e189b2b
X-Date: 1985-04-12T23:20:50.52Z

### find a firewall
# @name find
GET {{firewallbaseurl}}/find?project=test
Authorization: Metal-Admin 8d7b8a807d368b716ce7d712266b680edb77ff70d050be30e0bbf2e50e189b2b
X-Date: 1985-04-12T23:20:50.52Z
