@baseurl = {{scheme}}://{{host}}/v1/network

### get all networks
# @name getAll
GET {{baseurl}}
Authorization: Metal-Admin 8d7b8a807d368b716ce7d712266b680edb77ff70d050be30e0bbf2e50e189b2b
X-Date: 1985-04-12T23:20:50.52Z

### find network
POST {{baseurl}}/find
Content-Type: application/json
Authorization: Metal-Admin bfe5650d0149046959e7e49105134877906ebd6e1be0136dd6c51cb095d4ea8d
X-Date: 1985-04-12T23:20:50.52Z

{
  "partitionid": "vagrant"
}

### create project super network
# @name createProjectSuperNetwork
PUT {{baseurl}}/
Content-Type: application/json
Authorization: Metal-Admin ad24814d87cf57f35e1f075d02a7eb748d17536cbdff473c09be2b75df0ca4d0
X-Date: 1985-04-12T23:20:50.52Z

{
  "id": "tenant-super-network-vagrant",
  "description": "Project Super Network",
  "name": "projects",
  "nat": false,
  "partitionid": "vagrant",
  "prefixes": [
    "10.0.0.0/16"
  ],
  "privatesuper": true
}

### create internet network
# @name createInternetNetwork
PUT {{baseurl}}/
Content-Type: application/json
Authorization: Metal-Admin ad24814d87cf57f35e1f075d02a7eb748d17536cbdff473c09be2b75df0ca4d0
X-Date: 1985-04-12T23:20:50.52Z

{
  "id": "internet-vagrant",
  "description": "Internet in Vagrant",
  "name": "vagrant internet",
  "nat": false,
  "partitionid": "vagrant",
  "prefixes": [
    "185.24.0.0/16",
    "185.27.0.0/16"
  ],
  "privatesuper": false
}

### create underlay network
# @name createUnderlayNetwork
PUT {{baseurl}}/
Content-Type: application/json
Authorization: Metal-Admin ad24814d87cf57f35e1f075d02a7eb748d17536cbdff473c09be2b75df0ca4d0
X-Date: 1985-04-12T23:20:50.52Z

{
  "id": "underlay-vagrant",
  "description": "Underlay in Vagrant",
  "name": "vagrant underlay",
  "nat": false,
  "underlay": true,
  "partitionid": "vagrant",
  "vrf": 10000,
  "prefixes": [
    "10.1.0.0/24"
  ],
  "privatesuper": false
}

### allocate network
# @name allocateNetwork
POST {{baseurl}}/allocate
Content-Type: application/json
Authorization: Metal-Admin bfe5650d0149046959e7e49105134877906ebd6e1be0136dd6c51cb095d4ea8d
X-Date: 1985-04-12T23:20:50.52Z

{
  "projectid": "00000000-0000-0000-0000-000000000001",
  "partitionid": "vagrant"
}

### release network
# @name releaseNetwork
POST {{baseurl}}/release/f900e906-8b65-4262-892a-4dd4f520735d
Content-Type: application/json
Authorization: Metal-Admin bfe5650d0149046959e7e49105134877906ebd6e1be0136dd6c51cb095d4ea8d
X-Date: 1985-04-12T23:20:50.52Z


### delete network
# @name deleteNetwork
DELETE {{baseurl}}/tenant-super-network-vagrant
Content-Type: application/json
Authorization: Metal-Admin 60d4480107818d260233f835ff91ec85df194a2300b290e8aba4449246919d81
X-Date: 1985-04-12T23:20:50.52Z
