@baseurl = {{scheme}}://{{host}}/v1/network

### get all partitions
# @name getAll
GET {{baseurl}}

### create tenant network
# @name createTenantNetwork
PUT {{baseurl}}/
Content-Type: application/json
Authorization: Metal-Admin 8e99f348cb47cbb9f053bc768dd303d925dacfa2abc0a8fefc419d8459aa7583
X-Date: 1985-04-12T23:20:50.52Z

{
  "id": "primary-network",
  "description": "Tenant Super Network",
  "name": "tenants",
  "nat": false,
  "partitionid": "vagrant-lab",
  "prefixes": [
    "10.0.0.0/16"
  ],
  "primary": true
}

### create internet network
# @name createInternetNetwork
PUT {{baseurl}}/
Content-Type: application/json
Authorization: Metal-Admin 8e99f348cb47cbb9f053bc768dd303d925dacfa2abc0a8fefc419d8459aa7583
X-Date: 1985-04-12T23:20:50.52Z

{
  "id": "internet-vagrant-lab",
  "description": "Internet in Vagrant",
  "name": "vagrant internet",
  "nat": false,
  "partitionid": "vagrant-lab",
  "prefixes": [
    "185.24.0.0/16",
    "185.27.0.0/16"
  ],
  "primary": false
}

### create underlay network
# @name createUnderlayNetwork
PUT {{baseurl}}/
Content-Type: application/json

{
  "id": "underlay-vagrant-lab",
  "description": "Underlay in Vagrant",
  "name": "vagrant underlay",
  "nat": false,
  "underlay": true,
  "partitionid": "vagrant-lab",
  "prefixes": [
    "192.168.3.0/24"
  ],
  "primary": false
}

