@baseurl = {{scheme}}://{{host}}/v1/size

### get all switches
# @name getAll
GET {{baseurl}}

### get first size
@sizeid = {{getAll.response.body.$[0].id}}
# @name getFirstSize
GET {{baseurl}}/{{sizeid}}

### check if a size is found (success)
POST {{baseurl}}/fromHardware
Content-Type: application/json

{
    "cpu_cores": 1,
    "disks": [
      {
        "name": "sda",
        "size": 12
      },
      {
        "name": "sdb",
        "size": 13
      }
    ],
    "memory": 1024,
    "nics": [
      {
        "features": [
        ],
        "mac": "aa:aa:aa:aa:aa:aa",
        "name": "eth0",
        "vendor": "Dell",
        "neighbors": [
        	{
        		"mac":"11:11:11:11:11:11",
        		"name":"switch"
        	}
        ]
      },
      {
        "features": [
        ],
        "mac": "00:00:00:00:00:00",
        "name": "lo",
        "vendor": "Dell"
      }
    ]
}

### check if a size is found (no match)
POST {{baseurl}}/fromHardware
Content-Type: application/json

{
    "cpu_cores": 1,
    "disks": [
      {
        "name": "sda",
        "size": 12
      },
      {
        "name": "sdb",
        "size": 13
      }
    ],
    "memory": 10240,
    "nics": [
      {
        "features": [
        ],
        "mac": "aa:aa:aa:aa:aa:aa",
        "name": "eth0",
        "vendor": "Dell",
        "neighbors": [
        	{
        		"mac":"11:11:11:11:11:11",
        		"name":"switch"
        	}
        ]
      },
      {
        "features": [
        ],
        "mac": "00:00:00:00:00:00",
        "name": "lo",
        "vendor": "Dell"
      }
    ]
}