// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "git.f-i-ts.de/cloud-native/metal/metal-api/netbox-api/models"
)

// NetboxAPIProxyAPIMachineReleaseReader is a Reader for the NetboxAPIProxyAPIMachineRelease structure.
type NetboxAPIProxyAPIMachineReleaseReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *NetboxAPIProxyAPIMachineReleaseReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewNetboxAPIProxyAPIMachineReleaseOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewNetboxAPIProxyAPIMachineReleaseDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewNetboxAPIProxyAPIMachineReleaseOK creates a NetboxAPIProxyAPIMachineReleaseOK with default headers values
func NewNetboxAPIProxyAPIMachineReleaseOK() *NetboxAPIProxyAPIMachineReleaseOK {
	return &NetboxAPIProxyAPIMachineReleaseOK{}
}

/*NetboxAPIProxyAPIMachineReleaseOK handles this case with default header values.

OK
*/
type NetboxAPIProxyAPIMachineReleaseOK struct {
}

func (o *NetboxAPIProxyAPIMachineReleaseOK) Error() string {
	return fmt.Sprintf("[POST /machines/{uuid}/release][%d] netboxApiProxyApiMachineReleaseOK ", 200)
}

func (o *NetboxAPIProxyAPIMachineReleaseOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNetboxAPIProxyAPIMachineReleaseDefault creates a NetboxAPIProxyAPIMachineReleaseDefault with default headers values
func NewNetboxAPIProxyAPIMachineReleaseDefault(code int) *NetboxAPIProxyAPIMachineReleaseDefault {
	return &NetboxAPIProxyAPIMachineReleaseDefault{
		_statusCode: code,
	}
}

/*NetboxAPIProxyAPIMachineReleaseDefault handles this case with default header values.

Problem
*/
type NetboxAPIProxyAPIMachineReleaseDefault struct {
	_statusCode int

	Payload *models.Problem
}

// Code gets the status code for the netbox api proxy api machine release default response
func (o *NetboxAPIProxyAPIMachineReleaseDefault) Code() int {
	return o._statusCode
}

func (o *NetboxAPIProxyAPIMachineReleaseDefault) Error() string {
	return fmt.Sprintf("[POST /machines/{uuid}/release][%d] netbox_api_proxy.api.machine_release default  %+v", o._statusCode, o.Payload)
}

func (o *NetboxAPIProxyAPIMachineReleaseDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Problem)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
