// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewNetboxAPIProxyAPIMachineReleaseParams creates a new NetboxAPIProxyAPIMachineReleaseParams object
// with the default values initialized.
func NewNetboxAPIProxyAPIMachineReleaseParams() *NetboxAPIProxyAPIMachineReleaseParams {
	var ()
	return &NetboxAPIProxyAPIMachineReleaseParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewNetboxAPIProxyAPIMachineReleaseParamsWithTimeout creates a new NetboxAPIProxyAPIMachineReleaseParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewNetboxAPIProxyAPIMachineReleaseParamsWithTimeout(timeout time.Duration) *NetboxAPIProxyAPIMachineReleaseParams {
	var ()
	return &NetboxAPIProxyAPIMachineReleaseParams{

		timeout: timeout,
	}
}

// NewNetboxAPIProxyAPIMachineReleaseParamsWithContext creates a new NetboxAPIProxyAPIMachineReleaseParams object
// with the default values initialized, and the ability to set a context for a request
func NewNetboxAPIProxyAPIMachineReleaseParamsWithContext(ctx context.Context) *NetboxAPIProxyAPIMachineReleaseParams {
	var ()
	return &NetboxAPIProxyAPIMachineReleaseParams{

		Context: ctx,
	}
}

// NewNetboxAPIProxyAPIMachineReleaseParamsWithHTTPClient creates a new NetboxAPIProxyAPIMachineReleaseParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewNetboxAPIProxyAPIMachineReleaseParamsWithHTTPClient(client *http.Client) *NetboxAPIProxyAPIMachineReleaseParams {
	var ()
	return &NetboxAPIProxyAPIMachineReleaseParams{
		HTTPClient: client,
	}
}

/*NetboxAPIProxyAPIMachineReleaseParams contains all the parameters to send to the API endpoint
for the netbox api proxy api machine release operation typically these are written to a http.Request
*/
type NetboxAPIProxyAPIMachineReleaseParams struct {

	/*UUID
	  The product serial of the machine (unique identifier of this machine)

	*/
	UUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the netbox api proxy api machine release params
func (o *NetboxAPIProxyAPIMachineReleaseParams) WithTimeout(timeout time.Duration) *NetboxAPIProxyAPIMachineReleaseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the netbox api proxy api machine release params
func (o *NetboxAPIProxyAPIMachineReleaseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the netbox api proxy api machine release params
func (o *NetboxAPIProxyAPIMachineReleaseParams) WithContext(ctx context.Context) *NetboxAPIProxyAPIMachineReleaseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the netbox api proxy api machine release params
func (o *NetboxAPIProxyAPIMachineReleaseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the netbox api proxy api machine release params
func (o *NetboxAPIProxyAPIMachineReleaseParams) WithHTTPClient(client *http.Client) *NetboxAPIProxyAPIMachineReleaseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the netbox api proxy api machine release params
func (o *NetboxAPIProxyAPIMachineReleaseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUUID adds the uuid to the netbox api proxy api machine release params
func (o *NetboxAPIProxyAPIMachineReleaseParams) WithUUID(uuid string) *NetboxAPIProxyAPIMachineReleaseParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the netbox api proxy api machine release params
func (o *NetboxAPIProxyAPIMachineReleaseParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *NetboxAPIProxyAPIMachineReleaseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
