// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "git.f-i-ts.de/cloud-native/metal/metal-api/netbox-api/models"
)

// NewNetboxAPIProxyAPIMachineAllocateParams creates a new NetboxAPIProxyAPIMachineAllocateParams object
// with the default values initialized.
func NewNetboxAPIProxyAPIMachineAllocateParams() *NetboxAPIProxyAPIMachineAllocateParams {
	var ()
	return &NetboxAPIProxyAPIMachineAllocateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewNetboxAPIProxyAPIMachineAllocateParamsWithTimeout creates a new NetboxAPIProxyAPIMachineAllocateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewNetboxAPIProxyAPIMachineAllocateParamsWithTimeout(timeout time.Duration) *NetboxAPIProxyAPIMachineAllocateParams {
	var ()
	return &NetboxAPIProxyAPIMachineAllocateParams{

		timeout: timeout,
	}
}

// NewNetboxAPIProxyAPIMachineAllocateParamsWithContext creates a new NetboxAPIProxyAPIMachineAllocateParams object
// with the default values initialized, and the ability to set a context for a request
func NewNetboxAPIProxyAPIMachineAllocateParamsWithContext(ctx context.Context) *NetboxAPIProxyAPIMachineAllocateParams {
	var ()
	return &NetboxAPIProxyAPIMachineAllocateParams{

		Context: ctx,
	}
}

// NewNetboxAPIProxyAPIMachineAllocateParamsWithHTTPClient creates a new NetboxAPIProxyAPIMachineAllocateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewNetboxAPIProxyAPIMachineAllocateParamsWithHTTPClient(client *http.Client) *NetboxAPIProxyAPIMachineAllocateParams {
	var ()
	return &NetboxAPIProxyAPIMachineAllocateParams{
		HTTPClient: client,
	}
}

/*NetboxAPIProxyAPIMachineAllocateParams contains all the parameters to send to the API endpoint
for the netbox api proxy api machine allocate operation typically these are written to a http.Request
*/
type NetboxAPIProxyAPIMachineAllocateParams struct {

	/*Request
	  The machine allocation body

	*/
	Request *models.MachineAllocationRequest
	/*UUID
	  The product serial of the machine (unique identifier of this machine)

	*/
	UUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the netbox api proxy api machine allocate params
func (o *NetboxAPIProxyAPIMachineAllocateParams) WithTimeout(timeout time.Duration) *NetboxAPIProxyAPIMachineAllocateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the netbox api proxy api machine allocate params
func (o *NetboxAPIProxyAPIMachineAllocateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the netbox api proxy api machine allocate params
func (o *NetboxAPIProxyAPIMachineAllocateParams) WithContext(ctx context.Context) *NetboxAPIProxyAPIMachineAllocateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the netbox api proxy api machine allocate params
func (o *NetboxAPIProxyAPIMachineAllocateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the netbox api proxy api machine allocate params
func (o *NetboxAPIProxyAPIMachineAllocateParams) WithHTTPClient(client *http.Client) *NetboxAPIProxyAPIMachineAllocateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the netbox api proxy api machine allocate params
func (o *NetboxAPIProxyAPIMachineAllocateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the netbox api proxy api machine allocate params
func (o *NetboxAPIProxyAPIMachineAllocateParams) WithRequest(request *models.MachineAllocationRequest) *NetboxAPIProxyAPIMachineAllocateParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the netbox api proxy api machine allocate params
func (o *NetboxAPIProxyAPIMachineAllocateParams) SetRequest(request *models.MachineAllocationRequest) {
	o.Request = request
}

// WithUUID adds the uuid to the netbox api proxy api machine allocate params
func (o *NetboxAPIProxyAPIMachineAllocateParams) WithUUID(uuid string) *NetboxAPIProxyAPIMachineAllocateParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the netbox api proxy api machine allocate params
func (o *NetboxAPIProxyAPIMachineAllocateParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *NetboxAPIProxyAPIMachineAllocateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
