// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "git.f-i-ts.de/cloud-native/metal/metal-api/netbox-api/models"
)

// NewNetboxAPIProxyAPIMachineRegisterParams creates a new NetboxAPIProxyAPIMachineRegisterParams object
// with the default values initialized.
func NewNetboxAPIProxyAPIMachineRegisterParams() *NetboxAPIProxyAPIMachineRegisterParams {
	var ()
	return &NetboxAPIProxyAPIMachineRegisterParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewNetboxAPIProxyAPIMachineRegisterParamsWithTimeout creates a new NetboxAPIProxyAPIMachineRegisterParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewNetboxAPIProxyAPIMachineRegisterParamsWithTimeout(timeout time.Duration) *NetboxAPIProxyAPIMachineRegisterParams {
	var ()
	return &NetboxAPIProxyAPIMachineRegisterParams{

		timeout: timeout,
	}
}

// NewNetboxAPIProxyAPIMachineRegisterParamsWithContext creates a new NetboxAPIProxyAPIMachineRegisterParams object
// with the default values initialized, and the ability to set a context for a request
func NewNetboxAPIProxyAPIMachineRegisterParamsWithContext(ctx context.Context) *NetboxAPIProxyAPIMachineRegisterParams {
	var ()
	return &NetboxAPIProxyAPIMachineRegisterParams{

		Context: ctx,
	}
}

// NewNetboxAPIProxyAPIMachineRegisterParamsWithHTTPClient creates a new NetboxAPIProxyAPIMachineRegisterParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewNetboxAPIProxyAPIMachineRegisterParamsWithHTTPClient(client *http.Client) *NetboxAPIProxyAPIMachineRegisterParams {
	var ()
	return &NetboxAPIProxyAPIMachineRegisterParams{
		HTTPClient: client,
	}
}

/*NetboxAPIProxyAPIMachineRegisterParams contains all the parameters to send to the API endpoint
for the netbox api proxy api machine register operation typically these are written to a http.Request
*/
type NetboxAPIProxyAPIMachineRegisterParams struct {

	/*Request
	  The machine registration body

	*/
	Request *models.MachineRegistrationRequest
	/*UUID
	  The product serial of the machine (unique identifier of this machine)

	*/
	UUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the netbox api proxy api machine register params
func (o *NetboxAPIProxyAPIMachineRegisterParams) WithTimeout(timeout time.Duration) *NetboxAPIProxyAPIMachineRegisterParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the netbox api proxy api machine register params
func (o *NetboxAPIProxyAPIMachineRegisterParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the netbox api proxy api machine register params
func (o *NetboxAPIProxyAPIMachineRegisterParams) WithContext(ctx context.Context) *NetboxAPIProxyAPIMachineRegisterParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the netbox api proxy api machine register params
func (o *NetboxAPIProxyAPIMachineRegisterParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the netbox api proxy api machine register params
func (o *NetboxAPIProxyAPIMachineRegisterParams) WithHTTPClient(client *http.Client) *NetboxAPIProxyAPIMachineRegisterParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the netbox api proxy api machine register params
func (o *NetboxAPIProxyAPIMachineRegisterParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the netbox api proxy api machine register params
func (o *NetboxAPIProxyAPIMachineRegisterParams) WithRequest(request *models.MachineRegistrationRequest) *NetboxAPIProxyAPIMachineRegisterParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the netbox api proxy api machine register params
func (o *NetboxAPIProxyAPIMachineRegisterParams) SetRequest(request *models.MachineRegistrationRequest) {
	o.Request = request
}

// WithUUID adds the uuid to the netbox api proxy api machine register params
func (o *NetboxAPIProxyAPIMachineRegisterParams) WithUUID(uuid string) *NetboxAPIProxyAPIMachineRegisterParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the netbox api proxy api machine register params
func (o *NetboxAPIProxyAPIMachineRegisterParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *NetboxAPIProxyAPIMachineRegisterParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
