// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "git.f-i-ts.de/cloud-native/metal/metal-api/netbox-api/models"
)

// NetboxAPIProxyAPIMachineAllocateReader is a Reader for the NetboxAPIProxyAPIMachineAllocate structure.
type NetboxAPIProxyAPIMachineAllocateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *NetboxAPIProxyAPIMachineAllocateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewNetboxAPIProxyAPIMachineAllocateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewNetboxAPIProxyAPIMachineAllocateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewNetboxAPIProxyAPIMachineAllocateOK creates a NetboxAPIProxyAPIMachineAllocateOK with default headers values
func NewNetboxAPIProxyAPIMachineAllocateOK() *NetboxAPIProxyAPIMachineAllocateOK {
	return &NetboxAPIProxyAPIMachineAllocateOK{}
}

/*NetboxAPIProxyAPIMachineAllocateOK handles this case with default header values.

OK
*/
type NetboxAPIProxyAPIMachineAllocateOK struct {
}

func (o *NetboxAPIProxyAPIMachineAllocateOK) Error() string {
	return fmt.Sprintf("[POST /machines/{uuid}/allocate][%d] netboxApiProxyApiMachineAllocateOK ", 200)
}

func (o *NetboxAPIProxyAPIMachineAllocateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNetboxAPIProxyAPIMachineAllocateDefault creates a NetboxAPIProxyAPIMachineAllocateDefault with default headers values
func NewNetboxAPIProxyAPIMachineAllocateDefault(code int) *NetboxAPIProxyAPIMachineAllocateDefault {
	return &NetboxAPIProxyAPIMachineAllocateDefault{
		_statusCode: code,
	}
}

/*NetboxAPIProxyAPIMachineAllocateDefault handles this case with default header values.

Problem
*/
type NetboxAPIProxyAPIMachineAllocateDefault struct {
	_statusCode int

	Payload *models.Problem
}

// Code gets the status code for the netbox api proxy api machine allocate default response
func (o *NetboxAPIProxyAPIMachineAllocateDefault) Code() int {
	return o._statusCode
}

func (o *NetboxAPIProxyAPIMachineAllocateDefault) Error() string {
	return fmt.Sprintf("[POST /machines/{uuid}/allocate][%d] netbox_api_proxy.api.machine_allocate default  %+v", o._statusCode, o.Payload)
}

func (o *NetboxAPIProxyAPIMachineAllocateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Problem)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
