// Code generated by go-swagger; DO NOT EDIT.

package machines

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "git.f-i-ts.de/cloud-native/metal/metal-api/netbox-api/models"
)

// NetboxAPIProxyAPIMachineRegisterReader is a Reader for the NetboxAPIProxyAPIMachineRegister structure.
type NetboxAPIProxyAPIMachineRegisterReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *NetboxAPIProxyAPIMachineRegisterReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewNetboxAPIProxyAPIMachineRegisterOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewNetboxAPIProxyAPIMachineRegisterDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewNetboxAPIProxyAPIMachineRegisterOK creates a NetboxAPIProxyAPIMachineRegisterOK with default headers values
func NewNetboxAPIProxyAPIMachineRegisterOK() *NetboxAPIProxyAPIMachineRegisterOK {
	return &NetboxAPIProxyAPIMachineRegisterOK{}
}

/*NetboxAPIProxyAPIMachineRegisterOK handles this case with default header values.

OK
*/
type NetboxAPIProxyAPIMachineRegisterOK struct {
}

func (o *NetboxAPIProxyAPIMachineRegisterOK) Error() string {
	return fmt.Sprintf("[POST /machines/{uuid}/register][%d] netboxApiProxyApiMachineRegisterOK ", 200)
}

func (o *NetboxAPIProxyAPIMachineRegisterOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNetboxAPIProxyAPIMachineRegisterDefault creates a NetboxAPIProxyAPIMachineRegisterDefault with default headers values
func NewNetboxAPIProxyAPIMachineRegisterDefault(code int) *NetboxAPIProxyAPIMachineRegisterDefault {
	return &NetboxAPIProxyAPIMachineRegisterDefault{
		_statusCode: code,
	}
}

/*NetboxAPIProxyAPIMachineRegisterDefault handles this case with default header values.

Problem
*/
type NetboxAPIProxyAPIMachineRegisterDefault struct {
	_statusCode int

	Payload *models.Problem
}

// Code gets the status code for the netbox api proxy api machine register default response
func (o *NetboxAPIProxyAPIMachineRegisterDefault) Code() int {
	return o._statusCode
}

func (o *NetboxAPIProxyAPIMachineRegisterDefault) Error() string {
	return fmt.Sprintf("[POST /machines/{uuid}/register][%d] netbox_api_proxy.api.machine_register default  %+v", o._statusCode, o.Payload)
}

func (o *NetboxAPIProxyAPIMachineRegisterDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Problem)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
