// Code generated by go-swagger; DO NOT EDIT.

package ips

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new ips API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for ips API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
NetboxAPIProxyAPIAllocateIP creates an ip address from a prefix
*/
func (a *Client) NetboxAPIProxyAPIAllocateIP(params *NetboxAPIProxyAPIAllocateIPParams, authInfo runtime.ClientAuthInfoWriter) (*NetboxAPIProxyAPIAllocateIPOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewNetboxAPIProxyAPIAllocateIPParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "netbox_api_proxy.api.allocate_ip",
		Method:             "POST",
		PathPattern:        "/ips/allocate",
		ProducesMediaTypes: []string{"application/json", "application/problem+json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &NetboxAPIProxyAPIAllocateIPReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*NetboxAPIProxyAPIAllocateIPOK), nil

}

/*
NetboxAPIProxyAPIDeleteIP deletes an ip address
*/
func (a *Client) NetboxAPIProxyAPIDeleteIP(params *NetboxAPIProxyAPIDeleteIPParams, authInfo runtime.ClientAuthInfoWriter) (*NetboxAPIProxyAPIDeleteIPOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewNetboxAPIProxyAPIDeleteIPParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "netbox_api_proxy.api.delete_ip",
		Method:             "DELETE",
		PathPattern:        "/ips",
		ProducesMediaTypes: []string{"application/json", "application/problem+json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &NetboxAPIProxyAPIDeleteIPReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*NetboxAPIProxyAPIDeleteIPOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
