// Code generated by go-swagger; DO NOT EDIT.

package ips

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "git.f-i-ts.de/cloud-native/metal/metal-api/netbox-api/models"
)

// NewNetboxAPIProxyAPIAllocateIPParams creates a new NetboxAPIProxyAPIAllocateIPParams object
// with the default values initialized.
func NewNetboxAPIProxyAPIAllocateIPParams() *NetboxAPIProxyAPIAllocateIPParams {
	var ()
	return &NetboxAPIProxyAPIAllocateIPParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewNetboxAPIProxyAPIAllocateIPParamsWithTimeout creates a new NetboxAPIProxyAPIAllocateIPParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewNetboxAPIProxyAPIAllocateIPParamsWithTimeout(timeout time.Duration) *NetboxAPIProxyAPIAllocateIPParams {
	var ()
	return &NetboxAPIProxyAPIAllocateIPParams{

		timeout: timeout,
	}
}

// NewNetboxAPIProxyAPIAllocateIPParamsWithContext creates a new NetboxAPIProxyAPIAllocateIPParams object
// with the default values initialized, and the ability to set a context for a request
func NewNetboxAPIProxyAPIAllocateIPParamsWithContext(ctx context.Context) *NetboxAPIProxyAPIAllocateIPParams {
	var ()
	return &NetboxAPIProxyAPIAllocateIPParams{

		Context: ctx,
	}
}

// NewNetboxAPIProxyAPIAllocateIPParamsWithHTTPClient creates a new NetboxAPIProxyAPIAllocateIPParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewNetboxAPIProxyAPIAllocateIPParamsWithHTTPClient(client *http.Client) *NetboxAPIProxyAPIAllocateIPParams {
	var ()
	return &NetboxAPIProxyAPIAllocateIPParams{
		HTTPClient: client,
	}
}

/*NetboxAPIProxyAPIAllocateIPParams contains all the parameters to send to the API endpoint
for the netbox api proxy api allocate ip operation typically these are written to a http.Request
*/
type NetboxAPIProxyAPIAllocateIPParams struct {

	/*Request
	  The ip allocation body

	*/
	Request *models.IPAllocateRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the netbox api proxy api allocate ip params
func (o *NetboxAPIProxyAPIAllocateIPParams) WithTimeout(timeout time.Duration) *NetboxAPIProxyAPIAllocateIPParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the netbox api proxy api allocate ip params
func (o *NetboxAPIProxyAPIAllocateIPParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the netbox api proxy api allocate ip params
func (o *NetboxAPIProxyAPIAllocateIPParams) WithContext(ctx context.Context) *NetboxAPIProxyAPIAllocateIPParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the netbox api proxy api allocate ip params
func (o *NetboxAPIProxyAPIAllocateIPParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the netbox api proxy api allocate ip params
func (o *NetboxAPIProxyAPIAllocateIPParams) WithHTTPClient(client *http.Client) *NetboxAPIProxyAPIAllocateIPParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the netbox api proxy api allocate ip params
func (o *NetboxAPIProxyAPIAllocateIPParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the netbox api proxy api allocate ip params
func (o *NetboxAPIProxyAPIAllocateIPParams) WithRequest(request *models.IPAllocateRequest) *NetboxAPIProxyAPIAllocateIPParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the netbox api proxy api allocate ip params
func (o *NetboxAPIProxyAPIAllocateIPParams) SetRequest(request *models.IPAllocateRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *NetboxAPIProxyAPIAllocateIPParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
