// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "git.f-i-ts.de/cloud-native/maas/metal-api/netbox-api/models"
)

// NewLibServerAllocateDeviceParams creates a new LibServerAllocateDeviceParams object
// with the default values initialized.
func NewLibServerAllocateDeviceParams() *LibServerAllocateDeviceParams {
	var ()
	return &LibServerAllocateDeviceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewLibServerAllocateDeviceParamsWithTimeout creates a new LibServerAllocateDeviceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewLibServerAllocateDeviceParamsWithTimeout(timeout time.Duration) *LibServerAllocateDeviceParams {
	var ()
	return &LibServerAllocateDeviceParams{

		timeout: timeout,
	}
}

// NewLibServerAllocateDeviceParamsWithContext creates a new LibServerAllocateDeviceParams object
// with the default values initialized, and the ability to set a context for a request
func NewLibServerAllocateDeviceParamsWithContext(ctx context.Context) *LibServerAllocateDeviceParams {
	var ()
	return &LibServerAllocateDeviceParams{

		Context: ctx,
	}
}

// NewLibServerAllocateDeviceParamsWithHTTPClient creates a new LibServerAllocateDeviceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewLibServerAllocateDeviceParamsWithHTTPClient(client *http.Client) *LibServerAllocateDeviceParams {
	var ()
	return &LibServerAllocateDeviceParams{
		HTTPClient: client,
	}
}

/*LibServerAllocateDeviceParams contains all the parameters to send to the API endpoint
for the lib server allocate device operation typically these are written to a http.Request
*/
type LibServerAllocateDeviceParams struct {

	/*Request
	  The device allocation body

	*/
	Request *models.DeviceAllocationRequest
	/*UUID
	  The product serial of the device (unique identifier of this device)

	*/
	UUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the lib server allocate device params
func (o *LibServerAllocateDeviceParams) WithTimeout(timeout time.Duration) *LibServerAllocateDeviceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the lib server allocate device params
func (o *LibServerAllocateDeviceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the lib server allocate device params
func (o *LibServerAllocateDeviceParams) WithContext(ctx context.Context) *LibServerAllocateDeviceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the lib server allocate device params
func (o *LibServerAllocateDeviceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the lib server allocate device params
func (o *LibServerAllocateDeviceParams) WithHTTPClient(client *http.Client) *LibServerAllocateDeviceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the lib server allocate device params
func (o *LibServerAllocateDeviceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the lib server allocate device params
func (o *LibServerAllocateDeviceParams) WithRequest(request *models.DeviceAllocationRequest) *LibServerAllocateDeviceParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the lib server allocate device params
func (o *LibServerAllocateDeviceParams) SetRequest(request *models.DeviceAllocationRequest) {
	o.Request = request
}

// WithUUID adds the uuid to the lib server allocate device params
func (o *LibServerAllocateDeviceParams) WithUUID(uuid string) *LibServerAllocateDeviceParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the lib server allocate device params
func (o *LibServerAllocateDeviceParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *LibServerAllocateDeviceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
