// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "git.f-i-ts.de/cloud-native/maas/metal-api/netbox-api/models"
)

// NewLibServerRegisterDeviceParams creates a new LibServerRegisterDeviceParams object
// with the default values initialized.
func NewLibServerRegisterDeviceParams() *LibServerRegisterDeviceParams {
	var ()
	return &LibServerRegisterDeviceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewLibServerRegisterDeviceParamsWithTimeout creates a new LibServerRegisterDeviceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewLibServerRegisterDeviceParamsWithTimeout(timeout time.Duration) *LibServerRegisterDeviceParams {
	var ()
	return &LibServerRegisterDeviceParams{

		timeout: timeout,
	}
}

// NewLibServerRegisterDeviceParamsWithContext creates a new LibServerRegisterDeviceParams object
// with the default values initialized, and the ability to set a context for a request
func NewLibServerRegisterDeviceParamsWithContext(ctx context.Context) *LibServerRegisterDeviceParams {
	var ()
	return &LibServerRegisterDeviceParams{

		Context: ctx,
	}
}

// NewLibServerRegisterDeviceParamsWithHTTPClient creates a new LibServerRegisterDeviceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewLibServerRegisterDeviceParamsWithHTTPClient(client *http.Client) *LibServerRegisterDeviceParams {
	var ()
	return &LibServerRegisterDeviceParams{
		HTTPClient: client,
	}
}

/*LibServerRegisterDeviceParams contains all the parameters to send to the API endpoint
for the lib server register device operation typically these are written to a http.Request
*/
type LibServerRegisterDeviceParams struct {

	/*Request
	  The device registration body

	*/
	Request *models.DeviceRegistrationRequest
	/*UUID
	  The product serial of the device (unique identifier of this device)

	*/
	UUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the lib server register device params
func (o *LibServerRegisterDeviceParams) WithTimeout(timeout time.Duration) *LibServerRegisterDeviceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the lib server register device params
func (o *LibServerRegisterDeviceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the lib server register device params
func (o *LibServerRegisterDeviceParams) WithContext(ctx context.Context) *LibServerRegisterDeviceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the lib server register device params
func (o *LibServerRegisterDeviceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the lib server register device params
func (o *LibServerRegisterDeviceParams) WithHTTPClient(client *http.Client) *LibServerRegisterDeviceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the lib server register device params
func (o *LibServerRegisterDeviceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the lib server register device params
func (o *LibServerRegisterDeviceParams) WithRequest(request *models.DeviceRegistrationRequest) *LibServerRegisterDeviceParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the lib server register device params
func (o *LibServerRegisterDeviceParams) SetRequest(request *models.DeviceRegistrationRequest) {
	o.Request = request
}

// WithUUID adds the uuid to the lib server register device params
func (o *LibServerRegisterDeviceParams) WithUUID(uuid string) *LibServerRegisterDeviceParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the lib server register device params
func (o *LibServerRegisterDeviceParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *LibServerRegisterDeviceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
