// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewLibServerReleaseDeviceParams creates a new LibServerReleaseDeviceParams object
// with the default values initialized.
func NewLibServerReleaseDeviceParams() *LibServerReleaseDeviceParams {
	var ()
	return &LibServerReleaseDeviceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewLibServerReleaseDeviceParamsWithTimeout creates a new LibServerReleaseDeviceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewLibServerReleaseDeviceParamsWithTimeout(timeout time.Duration) *LibServerReleaseDeviceParams {
	var ()
	return &LibServerReleaseDeviceParams{

		timeout: timeout,
	}
}

// NewLibServerReleaseDeviceParamsWithContext creates a new LibServerReleaseDeviceParams object
// with the default values initialized, and the ability to set a context for a request
func NewLibServerReleaseDeviceParamsWithContext(ctx context.Context) *LibServerReleaseDeviceParams {
	var ()
	return &LibServerReleaseDeviceParams{

		Context: ctx,
	}
}

// NewLibServerReleaseDeviceParamsWithHTTPClient creates a new LibServerReleaseDeviceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewLibServerReleaseDeviceParamsWithHTTPClient(client *http.Client) *LibServerReleaseDeviceParams {
	var ()
	return &LibServerReleaseDeviceParams{
		HTTPClient: client,
	}
}

/*LibServerReleaseDeviceParams contains all the parameters to send to the API endpoint
for the lib server release device operation typically these are written to a http.Request
*/
type LibServerReleaseDeviceParams struct {

	/*UUID
	  The product serial of the device (unique identifier of this device)

	*/
	UUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the lib server release device params
func (o *LibServerReleaseDeviceParams) WithTimeout(timeout time.Duration) *LibServerReleaseDeviceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the lib server release device params
func (o *LibServerReleaseDeviceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the lib server release device params
func (o *LibServerReleaseDeviceParams) WithContext(ctx context.Context) *LibServerReleaseDeviceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the lib server release device params
func (o *LibServerReleaseDeviceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the lib server release device params
func (o *LibServerReleaseDeviceParams) WithHTTPClient(client *http.Client) *LibServerReleaseDeviceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the lib server release device params
func (o *LibServerReleaseDeviceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUUID adds the uuid to the lib server release device params
func (o *LibServerReleaseDeviceParams) WithUUID(uuid string) *LibServerReleaseDeviceParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the lib server release device params
func (o *LibServerReleaseDeviceParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *LibServerReleaseDeviceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
