name: Build tagged image

on:
  push:
    tags:
      - "v*"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}
    - name: Lint
      uses: actions-contrib/golangci-lint@master
      with:
        args: run
    - name: Build the Docker images
      run: |
        export GITHUB_TAG_NAME=${GITHUB_REF##*/}
        docker login -u metalstackci -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker build -t metalstack/metal-api:${GITHUB_TAG_NAME} .
        docker push metalstack/metal-api:${GITHUB_TAG_NAME}
